### ISSUE TITLE
add-stops modification

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#100]
Do we want to support inserting stops into the middle of an existing route/trip/pattern? This was part of some NL scenarios.

Travel times would have to be adjusted to account for dwell times at the stop. The proportion of hop times before and after the new stop would have to be set, and the total hop time may increase or decrease if the new stop is not along the existing route alignment.

Maybe there's another way to represent this. @mattwigway any opinions?

**Comment by mattwigway** [comment]
I'd say we don't represent portions of the existing hop time but rather create something akin to Javascript's [Array.splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice). So we'd have from_stop, to_stop, and a list of hop and dwell times. All stops between the from and to stop would be removed and replaced with the new stops, hops and dwell times. This could be used to represent a single stop insertion or a more complex reroute.

However, it might also be wise to ensure that routes modified in this way are converted to frequencies; once you've made a major reroute, preserving the existing schedule is probably inadvisable.

**Comment by mattwigway** [comment]
One other wrinkle with from_stop, to_stop etc: we need to come up with some way to adjust the termini of the route. I'd propose that leaving from_stop null replaces all stops up to to_stop exclusive.

**Comment by abyrd** [comment]
Just to confirm what I said in a voice conversation recently, I think this is a great way to do it: splicing new chunks of timetable in between the given stops on the pattern. We also decided to be somewhat conservative about frequency-converting everything though, because we want to avoid conversion magic. We should be able to (commutatively?) apply an insert stops modification and an adjust-frequency modification together.

**Comment by mattwigway** [comment]
Here's what the modification will look like (for a modification in the middle of a pattern):

{
      "type": "add-stop",
      "fromStop": "Jan2016-GTFS-v6:STEMONN",
      "toStop": "Jan2016-GTFS-v6:STE418N",
      // alternately, specify trip IDs
      "routes": [
        "Jan2016-GTFS-v6:016"
      ],
      "stops": [
        {
          "lon": -82.90896892547607,
          "lat": 40.04962826468526
        }
      ],
      "hopTimes": [
        60,
        60
      ],
      "dwellTimes": [
        0,
        0,
        0
      ]
    }

**Comment by mattwigway** [comment]
And here's what it would look like for the end of the pattern:

```
    {
      "type": "add-stop",
      "fromStop": "Jan2016-GTFS-v6:HAM5THN",
      "toStop": null,
      "routes": [
        "Jan2016-GTFS-v6:089"
      ],
      "stops": [
        {
          "stopId": "Jan2016-GTFS-v6:HAMAIRN"
        },
        {
          "stopId": "Jan2016-GTFS-v6:PORGRON"
        }
      ],
      "hopTimes": [
        60,
        60
      ],
      "dwellTimes": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
```

**Comment by mattwigway** [comment]
And the start of a pattern:

```
   {
      "type": "add-stop",
      "fromStop": null,
      "toStop": "Jan2016-GTFS-v6:KAR161S1",
      "routes": [
        "Jan2016-GTFS-v6:034"
      ],
      "stops": [
        {
          "stopId": "Jan2016-GTFS-v6:AMBSEAS"
        },
        {
          "stopId": "Jan2016-GTFS-v6:KAR161S"
        }
      ],
      "hopTimes": [
        60,
        60
      ],
      "dwellTimes": [
        0,
        0,
        0
      ]
    }
```

**Comment by abyrd** [comment]
I think "type" should be "add-stops" (plural) to match the other modifications.

**Comment by mattwigway** [comment]
woops, typo on my part. I'll fix scenario editor.

**Comment by abyrd** [comment]
Although this is now general enough that it is multi-purpose: add/insert/replace stops.

**Comment by mattwigway** [comment]
It could be called reroute also.

**Comment by mattwigway** [comment]
@abyrd: can we make the ID field to reference an existing stop just be called `id` to match `add-trips` (#94)?

**Comment by abyrd** [comment]
Sure, we should be reusing the same classes on the Java side anyway.

**Comment by abyrd** [comment]
This modification can also be used to remove stops from a route without adding any stops at all, so we should rename it sooner than later. It always inserts or replaces hops, but not always stops. "Reroute" seems like a good name. 

Another thing that should be clarified: whether we're inserting hops at the beginning, middle, or end of the route (i.e whether fromStop and toStop are specified or not) the number of dwell times should always be one more than the number of hop times provided. That is to say, we never preserve the dwell times at fromStop or toStop in the original pattern, they are always overwritten by the first or last supplied dwell time. 

The examples above on this ticket follow this rule, but the output from the scenario editor currently does not. Preserving the dwell times at fromStop and toStop does not seem very important to me. Always overwriting them makes the rules for validating the modification message simpler. It also makes the code to apply the modification more readable, and probably likewise for the code to generate the modification message.

**Comment by abyrd** [comment]
On the other hand, in the modifications produced by the scenario editor the number of dwells exactly matches the number of supplied stop IDs. This also has nice properties. We can stick with this representation, but we just need to state which one we're using.

**Comment by mattwigway** [comment]
I think there should always be dwell times for all added stops, and fromStop and toStop (if supplied). This is important because when you extend the end of a route, you often need to add a dwell time to the first or last stop in the existing pattern because the vehicle now continues past that stop rather than originating/terminating there (i.e. the arrival time at the first stop and the departure time at the last stop in the original modification are now relevant).

**Comment by abyrd** [comment]
Decided today in conversation with @mattwigway: the number of dwell times in the modification must always be one greater than the number of hop times. That is to say we supply one dwell time before and after every hop time like so: O=O=O=O=O

The number of dwell times must be equal to the number of inserted stops, plus one dwell for fromStop and one dwell for toStop when they are specified.

That is to say, a dwell time is supplied for each "anchor stop" referenced in the original trip pattern, and one more for each stop in the stops list. For N dwells, enough hops are supplied to tie them all together (N-1 hops).
