### ISSUE TITLE
Remove TRANSIT from Mode?

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#102]
Originally mentioned in #101. I'm making this a separate ticket.

We now have two mode enums, one for types of transit and one for on-street modes (which happens to still have a TRANSIT member).

@buma should Mode be renamed to something like StreetMode, and should we remove TRANSIT as one of its members?

**Comment by buma** [comment]
This should probably be renamed to StreetMode. And I'm not sure why it has Transit in it. @mattwigway Any idea?

**Comment by abyrd** [comment]
It contains transit because it was originally intended to represent all the modes, when there were no separate street and transit modes parameters.
