### ISSUE TITLE
McRaptorSuboptimalPathProfileRouter doesn't check if trip even runs on wanted date

### ISSUE THREAD

**Issue by buma** [conveyal/r5#110]
@mattwigway noticed that R5 uses weekend service on weekdays in #107. This was fixed. But McRaptorSuboptimalPathProfileRouter doesn't check anywhere if tripPattern or trip even runs on specified dates. I noticed now when I have more debug output and I also see services of chosen trips. Sometimes in multi transit trip you get first transit trip on service which runs during a week and second part of service which runs on weekend.

**Comment by mattwigway** [comment]
That's weird. I don't remember assigning this to you. Maybe Waffle did that?

**Comment by buma** [comment]
Maybe. But I made PR for this already I just don't know if it is fully correct. So It would be great if you look over it.

**Comment by mattwigway** [comment]
I'll take a look this afternoon.

On Thu, Apr 7, 2016 at 9:43 AM, Marko Burjek <notifications@github.com>
wrote:

> Maybe. But I made PR for this already I just don't know if it is fully
> correct. So It would be great if you look over it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/110#issuecomment-206910474>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
Ah well, waffle does automatically assign issues when a PR is created: https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking

I think I don't like that.
