### ISSUE TITLE
All-to-all mass of transit on an island

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#112]
Using NL data cropped to the Amsterdam Regional study area, the island of Texel exhibits a bizarre many-to-many web of lines:
![image](https://cloud.githubusercontent.com/assets/112871/14289875/07f30358-fb5d-11e5-918f-5b31763863ab.png)

**Comment by mattwigway** [comment]
That would be a handy transit system.

**Comment by mattwigway** [comment]
I think this is probably an issue in Analyst Server.

**Comment by ansoncfit** [comment]
Have not seen this issue in ~2 years, closing.

**Comment by mattwigway** [comment]
Guess we never noted this on this ticket; this is not a bug. The transit
system on that island is 100% demand response, and is coded in the GTFS as
a route from every stop to every other stop.

**Comment by abyrd** [comment]
Right, this was a workaround for lack of demand-responsive transit. We expect to support proper descriptions of this kind of transit in future versions of OTP or R5 via the GTFS and/or Netex flex specifications.
