### ISSUE TITLE
Sort out weight, time and distance in stop trees

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#117]
Looking at the stop trees in linkedpointset it's not entirely clear what they're supposed to contain. It seems [they are intended to contain meters](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/streets/LinkedPointSet.java#L170) but are using state weight, which also [includes turn costs](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/streets/EdgeStore.java#L538). In RaptorWorker we are using them as [times directly, not distances](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/profile/RaptorWorker.java#L763).

This explained almost all of the difference in results between RaptorWorker and the McRaptor algorithm.

**Comment by abyrd** [comment]
In getStopTree a weight (including turn costs) is being divided by a hardwired 1.3 m/sec walk speed. Yes, clearly we need to iron this out.

**Comment by mattwigway** [comment]
We are going to convert all stop trees in r5 (and I'll do the transfers as well) to store distances in millimeters, which solves the floating-point math problem (we can do int math with millimeters and millimeters per second and get answers that are totally acceptable). MAX_INT millimeters is 2,147 km, which should be sufficient for (ahem) pedestrian use, and indeed anything we might throw at it.
