### ISSUE TITLE
Make sure multiple frequency entries work correctly

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#121]
The input GTFS for the fare project we're working on for the world bank comes from [geom2gtfs](https://github.com/conveyal/geom2gtfs). This means that it has multiple frequency entries per trip (for different time windows). This doesn't work right in gtfs-lib, at least when writing GTFS (conveyal/gtfs-lib#10). We should make sure (1) that the gtfs-lib issue is confined to writing, and (2) that r5 handles this case correctly.

**Comment by mattwigway** [comment]
Well they definitely didn't work before, but they still need more testing.

**Comment by ansoncfit** [comment]
Tested ✔️
