### ISSUE TITLE
Length of hopTimes, dwellTimes arrays not enforced in AddTrips

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#132]
It is possible to have an addTrips modification with the wrong length array for hopTimes or dwellTimes; in fact, there is code that checks the length and sets hops/dwells beyond the length of the array to 0. This seems like a bug but it's clear some effort was put into making it work this way, so I'm wondering if it's intentional.

![image](https://cloud.githubusercontent.com/assets/566958/14800482/f95aa1ee-0b0f-11e6-9dcf-749136659793.png)

**Comment by mattwigway** [comment]
(that code is in AddTrips.java)

**Comment by abyrd** [comment]
This was done a while back, driven mostly by the experience of hand-writing the JSON. I think the main case it was handling was a completely empty dwells array. Indeed it's not a wise thing to retain. Now that we're using only machine-generated JSON this should be removed, and we'll verify that the dwell times array length exactly matches the number of stops.

**Comment by mattwigway** [comment]
We could also just allow dwellTimes to be null. But we should make sure that if it is specified, it is the same length as the number of stops.
