### ISSUE TITLE
Label bikeable roads by level of traffic stress

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#14]
See http://transweb.sjsu.edu/PDFs/research/1005-low-stress-bicycling-network-connectivity.pdf .

OSM doesn't have enough data to implement the LTS methodology directly (esp. with regard to lane widths), but we can likely approximate it using roadway classifications.

Of course the problem will be how you define a scenario then. If your scenario is to widen a bike lane or remove a car lane, be don't have a good way to model that in OSM.

**Comment by buma** [comment]
Is this connected to this [class:bicycle](https://wiki.openstreetmap.org/wiki/Class:bicycle) tag?
