### ISSUE TITLE
Add trips is creating timetables not frequencies

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#140]
Per https://github.com/conveyal/r5/issues/94#issuecomment-193934706 , there should not be a `frequency` flag in add-trips entries, as everything is a frequency. However in the code we are checking this flag and creating bona fide trips if it is false: https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java#L245

This is particularly egregious because it's non-obvious, as trips are created at the specified headway, they just aren't moved around in the Monte Carlo simulation (it's as if exact_times were set to true, and if we properly supported exact_times).

**Comment by abyrd** [comment]
Yes particularly bad that frequency defaults to false. I'll rip this out.

**Comment by abyrd** [comment]
The problem is that this leaves us with no way to specify exact timetables for newly added patterns. I imagine someone will eventually want to do that.

**Comment by mattwigway** [comment]
We had decided not to support that in the linked comment.

**Comment by abyrd** [comment]
If we ever want to add timetables instead of frequencies, we'll send over the entire timetable in the modification message. We'll probably never use exact_times style generated timetables.
