### ISSUE TITLE
Prune based on maxFare during search

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#141]
We currently don't do pruning based on maxFare during the McRAPTOR search but rather do it at propagation, which means we're exploring a lot of paths that are too expensive to wind up in the final output.

At the moment we're not trying to vary the fare cutoff after the fact.

This should speed up computation significantly when the fare cutoff is significantly binding.

**Comment by ansoncfit** [comment]
Addressed in https://github.com/conveyal/r5/commit/e008a8f9e1bc26de83a2ad091e613ce924075f4a
