### ISSUE TITLE
Choose number of iterations for RAPTOR algorithm

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#142]
We should specify this in the profile request.

**Comment by abyrd** [comment]
By "number of iterations" do you mean number of Monte Carlo draws? I ask because there are many different things being iterated over in RAPTOR.

**Comment by mattwigway** [comment]
Actually, I just meant number of monte carlo draws; the number of departure minutes is specified by fromTime and toTime. In a combined frequency-schedule network, if you requested 1200 draws, and 120 minutes, you'd get 10 draws per minute. We'll round up, so if you requested 1200 draws and 121 minutes, you'd still get 10 draws per minute (1200 / 121 = 9.92).

**Comment by abyrd** [comment]
Thanks for the clarification, I thought you wanted to do the random walk method.

**Comment by mattwigway** [comment]
I don't see any reason to do that. I suspect that in the scheduled network, changing the resolution doesn't do a whole lot due to range-raptor.

**Comment by mattwigway** [comment]
I should expand upon that. As you increase the sampling frequency, due to range raptor each iteration does less work. Of course range-RAPTOR doesn't apply in the frequency case.
