### ISSUE TITLE
rename add-stops modification

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#146]
While adding or removing stops from the original pattern or even leaving them untouched, this modification extends and/or overwrites it. The only verb that seems to cover all these cases is "reroute". @mattwigway can you change the name on the editor side (not necessarily in the data storage but in the output modification messages) and I'll change it in R5?

**Comment by mattwigway** [comment]
Done. I'll need to change the UI and the names of classes in the codebase at some point but for the purposes of stabilizing the API we're good (it now outputs add-stops modifications with type 'reroute')
