### ISSUE TITLE
Sort added schedule trips by start time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#153]
Scheduled trips need to be sorted by start time so that RaptorWorker functions correctly, when adding trips using AdjustFrequency they currently are not.

**Comment by abyrd** [comment]
Or alternatively we just don't break out of the boarding search until it's seen all trips. Using sorted trip times may currently provide a speedup, but as far as I can tell we're currently performing way too many boarding searches (see TODOs in code).

If for whatever reason we ever apply real-time changes to the timetables, keeping them sorted becomes a problem. In past experience, just doing linear searches without assuming sorting is reasonably fast.
