### ISSUE TITLE
Non-transit times are slightly incorrect when there is a turn restriction at the destination

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#155]
We're using `StreetRouter::getTravelTimeToVertex` to create `PointSetTimes` to feed to `RaptorWorker` as non-transit times. However, each of those points in that pointset is itself a split, so we should really be using the code in streetrouter that gets the travel time to a split. This is important when there are turn restrictions or turn costs onto the final edge.

**Comment by mattwigway** [comment]
The same problem exists in `LinkedPointSet::link`

**Comment by abyrd** [comment]
Closing, merged into #764.
