### ISSUE TITLE
Make destination linking deterministic

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#159]
We often use census blocks as our destination polygons. The "Tiger Line" road centerline data that was bulk imported into OpenStreetMap is the same data used to create the US census blocks. Therefore the centroids of our destination polygons are often precisely the same distance from two different streets. Our process for connecting the destination centroid to a street chooses the closest street, and happens to break ties by choosing the first one in the collection of nearby streets returned from the spatial index. That collection is a Set, and whenever temporary edges are added to the graph they also are dropped into that Set. Therefore when street modifications are applied in a scenario, the size of the Set changes and its iteration order may change. This can cause the destination to be re-linked to another equidistant street, sometimes making it much closer or farther from a transit stop.

One long-term solution is to never use blocks, but to instead use an uncorrelated regular grid. In that case it's quite unlikely that any centroids will be equidistant to several roads. It will also help ensure that any error that does occur is randomly distributed.

However on principle we should also ensure that linking is deterministic. Fortunately in R5 edges have integer IDs, so we can just break ties by linking to the smallest integer ID. We could also switch to using integer math, which should be both faster and less prone to numerical weirdness.

**Comment by mattwigway** [comment]
@abyrd we can close this, right?

**Comment by abyrd** [comment]
Yes, this is supposed to be fixed. I'm closing it.
