### ISSUE TITLE
Sparse networks make analysis extremely sensitive to time window chosen since we have disabled the maximum travel time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#162]
Consider the case of a peak only bus that departs every 30 minutes from 6-8 AM and then stops running until 4pm. For the purposes of this exercise, let's assume that it runs in both directions during both peaks, and let's also assume there's no alternate service (local buses etc.) that can get you from your origin to your destination. Consider when you set your time window to 6:30-7:30 AM: you may have pretty good accessibility because this express bus will get you on the network very quickly. Now consider 7:30 to 8:30: for that last 30 minutes, you have to wait until 4pm. We're computing an average travel time, and that extra 8 hours of waiting will really pull up that travel time.

We had previously addressed this by cutting off the search after a particular time and then considering destinations that cannot be reached in that time "unreachable" and dealing with them using reachability thresholds. At some point we turned off this cutoff. Unfortunately it doesn't have a well-defined value; the correct value should be somewhat above the maximum average travel time you're interested in, because otherwise you'll bias averages downwards (if the trip takes between 100 and 150 minutes, and on average 110, you don't want to eliminate all minutes over 120, as the average will be pulled artificially low). Pulling this off is a little tricky as to do it right you have to re-prune the tree as range-RAPTOR results fall past the cutoff (so for instance if your cutoff is 3 hours, if there was a 2:48 trip at 9 AM, at 8:47 AM you have to remove that trip from the range-RAPTOR output tables).

Another option is to limit the waiting time, rather than the overall trip length. We already do this with walking time so it's not crazy.

This is not a hypothetical concern. Consider the following transit system (the yellow isochrone is irrelevant; consider only the blue isochrone):

7:00 - 7:45 AM:

![image](https://cloud.githubusercontent.com/assets/566958/15614764/842b648c-2408-11e6-9839-3c5f5d9b687d.png)

7:00 - 8:00 AM:

![image](https://cloud.githubusercontent.com/assets/566958/15614757/7775ad1a-2408-11e6-9619-f5c3a8aa8228.png)

If we turn the trip length limit back on, things work as expected (7–8 AM, now looking at the yellow isochrone):

![image](https://cloud.githubusercontent.com/assets/566958/15614813/c2ff586c-2408-11e6-81bd-3bb26da78c7f.png)

I kind of prefer the wait time limit to the trip length limit, but I don't really like either. It's another arbitrary parameter that has major effects on the results.

**Comment by mattwigway** [comment]
The wait time limit won't work, the planner will cunningly work around that limit and still get on the later vehicle by riding buses the wrong direction, taking long walks to transfer to other buses, etc., eventually eating up all the time until that later trip. The results would then be even less clear, as they would be speckled. If the origin had no other transit service, the planner would not be able to find a way to kill enough time, and the destination would be considered unreachable. However, if the origin had a network of local buses that don't go to the destination, the planner might be able to kill all day riding buses (without visiting the same stop twice) and still get on the late afternoon vehicle.

**Comment by abyrd** [comment]
However, as noted in #169 once we've finished our current round of analysis based on average travel times it appears we can completely sidestep all these arbitrary limits and thresholds by just using percentiles instead of averages.

**Comment by mattwigway** [comment]
Max time limit has been reëstablished.
