### ISSUE TITLE
Park and Ride support

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#17]
We need to detect park and rides in OSM data and connect them to nearby stations. Rather than spawning new "incomparable layers" of Dijkstra search as in OTP, we should probably just add explicit edges from the parking lots to nearby stops. 

This is a priority feature for @chourmo for Marseille.

**Comment by buma** [comment]
I added car speeds to TransitNetwork and debug client in https://github.com/conveyal/r5/tree/jsonConfigSupport branch. Speeds currently aren't used in routing since time needs to be added to states.

**Comment by buma** [comment]
I think this can be closed since we have #44
