### ISSUE TITLE
Deleting bundle does not delete scenarios

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#178]
I created a "bundle" and a baseline (empty) scenario was created for it. After various problems I deleted this bundle and re-uploaded it under a similar name. Afterward multiple empty baseline scenarios existed, including one referencing the now-deleted bundle. Analyses were simply failing with the "analysis failed" message. After a long time I realized this was because in the analysis the scenario referencing the deleted bundle was selected.

Scenarios should never be able to outlive the data bundles they reference.

**Comment by ansoncfit** [comment]
Effectively solved by https://github.com/conveyal/analysis-ui/pull/1031
