### ISSUE TITLE
More logging on analyst worker 

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#18]
The first time you do an analysis via the analyst web UI, it reports "processing query" for a long time. Even when all components are running locally, there is no sign from any component that any long-running operation is in progress, or even that it has started. This leaves you wondering if it's actually doing anything or just stalled. We should log the beginning and end of any potentially slow one-off operation.

**Comment by abyrd** [comment]
This is especially necessary when testing locally because there is a lot of data transfer to and from Amazon S3. On an ADSL connection this can be extremely slow (uploading 100MB PBF files at 250kB/sec). It helps to at least have some indication of what's happening or the whole system feels broken.

**Comment by buma** [comment]
I use [BSDiff](http://www.daemonology.net/bsdiff/) for uploading new Jars and Graph.obj files to my server. It is meant for binary diffs. I do a local diff between previous and new JAR/Graph and upload a difference. Then on server apply a diff to old file and I have a new file. 

For example OTP.jar has 39 MB but diff is 1.8 MB. Graph has 36MB and diff has 297 kB. There is also [java implementation](https://github.com/malensek/jbsdiff) one of many. I scripted this with [Fabric](http://www.fabfile.org/). It would probably also work on PBF files.

**Comment by abyrd** [comment]
In production, these file transfers are extremely fast because all the machines in use are in the same data center and have very fast network links. It's really only a problem when testing on an ADSL connection. But in either case it's still nice to have log entries showing when various actions are happening, to follow progress.

**Comment by abyrd** [comment]
Actually, the commit above is totally mislabeled. It reduces the amount of logging by making the polling DEBUG level.

**Comment by ansoncfit** [comment]
Largely addressed by work in R5 on https://github.com/conveyal/r5/issues/444
