### ISSUE TITLE
Turn restriction code is very slow

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#189]
I think this is probably because where there are adjacent turn restrictions we are driving around the block until we hit the distance limit because every state is in a turn restriction, and the states are not comparable. We should first confirm this is happening (check how many states there are at each edge in bestStatesAtEdge; there should never be more than ~5), and if so make states comparable if they are in the same set of turn restrictions.

**Comment by mattwigway** [comment]
It looks like th einfinite loop problem was already fixed in #88.

**Comment by abyrd** [comment]
Closing, merged into #764.
