### ISSUE TITLE
Obvious simpler, faster itineraries not returned

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#198]
I'm doing point-to-point routing on a network for Singapore that I exported from a Matsim model. I'm using http://localhost:8080/new.html to trigger some searches and seeing what seem like incorrect results.

If I route from Joo Koon on the East-West rail line to Jurong East (an interchange station between the East-West (EW) and North-South (NS) lines, and the terminus of the NS line), I get the expected result that EW is the only reasonable transit option with a 13 minute ride:
![image](https://cloud.githubusercontent.com/assets/112871/19510117/6510da90-9614-11e6-92a5-04644deb7264.png)

Then if I search from Jurong East to Woodlands, the NS line is the only reasonable transit option, a 17 minute ride:

![image](https://cloud.githubusercontent.com/assets/112871/19510231/daab8cdc-9614-11e6-8c77-cb8e78bc76b7.png)

However, if I search from Joo Koon to Woodlands, I get a slew of three-bus options all taking about 1.5 hours. The obvious option of riding two trains and transferring at Jurong, which should take only half an hour, does not appear at all:

![image](https://cloud.githubusercontent.com/assets/112871/19510322/526a67f2-9615-11e6-8dd6-a5f00ecf40a1.png)

**Comment by abyrd** [comment]
I've verified that R5 has constructed transfers between stops NS1 and EW24 (the two platforms at Jurong East) and the distances look reasonable.

**Comment by abyrd** [comment]
I think I see the problem. McRaptorSuboptimalPathProfileRouter#doTransfers takes the distance from the packed transfer table (units millimeters) and adds it to a time variable (units seconds). This might have provided a rough estimate when our distances were in meters, but now that they are in millimeters it vastly overestimates transfer distances, basically ruling out any transfers at all that do not involve departing from the same stop where you arrived.

We should really be using clear symbolic variable names anywhere units are relevant. I'll do so in my patch to this code.

However, when I properly convert millimeters to seconds R5 always throws an error when the search completes:

```
java.lang.IllegalStateException: No valid itineraries found for path computed in RaptorWorker
	at com.conveyal.r5.profile.PathWithTimes.computeStatistics(PathWithTimes.java:197) ~[classes/:na]
	at com.conveyal.r5.profile.PathWithTimes.computeTimes(PathWithTimes.java:130) ~[classes/:na]
	at com.conveyal.r5.profile.PathWithTimes.<init>(PathWithTimes.java:135) ~[classes/:na]
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.lambda$getPaths$4(McRaptorSuboptimalPathProfileRouter.java:258) ~[classes/:na]
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter$$Lambda$218/1307842513.accept(Unknown Source) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_31]
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.getPaths(McRaptorSuboptimalPathProfileRouter.java:257) ~[classes/:na]
	at com.conveyal.r5.point_to_point.builder.PointToPointQuery.getPlan(PointToPointQuery.java:115) ~[classes/:na]
	at com.conveyal.r5.GraphQLSchema.lambda$new$212(GraphQLSchema.java:1530) ~[classes/:na]
```

**Comment by buma** [comment]
Wouldn't be better if transfers are saved with times instead of distances. Or are they used somewhere else with distances?

**Comment by abyrd** [comment]
Saving them with times would make it impossible to change the walk speed.

**Comment by abyrd** [comment]
That kind of thing would be an optimization. My main concern currently is that changing this method to use correct walk distances, or even to use artificial but reasonably small walk distances, always results in "No valid itineraries found for path".

**Comment by abyrd** [comment]
After changing transfer distance handling in two places, things are looking better:
![image](https://cloud.githubusercontent.com/assets/112871/19515500/631696ba-962a-11e6-9bc9-54a4b6b9219c.png)

We need to do a complete audit to make sure transfer distances are not being misused elsewhere before closing this ticket.
