### ISSUE TITLE
Get transit info in debug interface

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#200]
Using our debug interface at http://localhost:8080/debug.html we can see lots of information about street edges. Transit stops are visible on the map but we can't fetch any information about them. It would be really useful to be able to pop up / mark them with stop IDs and internal stop index numbers, and also get a list of routes/patterns running through them.

**Comment by buma** [comment]
Stops, P+R and bikeshares are currently shown in /new.html. Stops also have name, StopID and MODE. Bike shares have name,id P+R have also capacity. I can try to add this to debug also together with routes/pattern.

**Comment by abyrd** [comment]
Oh nice. Thanks @buma. It's fine if I can just see them in new.html. I do still have a problem there though: if two stops are in exactly the same place you can only click on the top one.

**Comment by buma** [comment]
I'll add jitter.

**Comment by buma** [comment]
Jitter added. And I forgot. Color of stops is also based on MODE.
