### ISSUE TITLE
PointSet cache, base linkages and distance tables are lost

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#217]
Quickly getting started doing computations on worker startup will require the basic GridPointSet and its linkage to be deserialized with the TransportNetwork. However, these Guava caches do not serialize their contents.

We will have to either implement our own cache class (which might actually be a good thing for keeping memory consumption under control) capable of serializing its contents, or just save the linkage in a field on the network or the streetlayer.

This is going to depend on whether we want to support multiple different pointsets on a network, or we're just using only grids.

**Comment by abyrd** [comment]
Another argument in favor of writing our own cache class: we want to key the cache of linkages on the street layer's contents ID String (not the identity of the street layer object). But when the linkage is absent, we need the ID of the street layer from which the new street layer is derived, and we need to fetch the linkage for that layer from the cache, so we need to get the whole StreetLayer object into the get() function. That is to say, the type of the cache key is distinct from the type of the object we need to compute a new cache value.

**Comment by abyrd** [comment]
I was really overthinking the cache keying problem. We selectively relink pointsets now, so relinking a pointset can now just mean copying it and doing nothing to the copy, because nothing has changed in the streetlayer we're linking to. This still wastes space as the linkage is duplicated, but it may be a better path forward than caching. The relinking method could detect when nothing has changed and just return a reference to the same linkage.

**Comment by abyrd** [comment]
So apparently these are somehow getting serialized because today we started up two NL workers that immediately started generating results with no long linking stage. It remains to be discovered why this suddenly worked as designed.

**Comment by abyrd** [comment]
It turns out this was fixed in January 2017, and we build one base linked pointset that's always saved with the network and loaded into the cache as soon as the network is deserialized. This creates other problems (see #383) but it does mean that workers should start up very fast. It's not clear why we were having problems with slow startup and repeated re-linking. The problems must still exist (we did nothing additional to fix them) so they must just come and go.

**Comment by ansoncfit** [comment]
This agrees with what I observed during a training a few months ago.  I ran requests using all access modes ahead of the training, so that users would not experience timeouts while distance tables were built.  But partway through the training, I noticed the worker rebuilding distance tables, which suggests they had been evicted.
