### ISSUE TITLE
Car routing fails when origin gets snapped to one-way cul-de-sac

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#228]
Car routing fails when the origin is snapped to [this way](http://www.openstreetmap.org/way/207971576) which is a one-way street that dead-ends into the entrance of a parking garage, but the interior of the parking garage is not mapped.

We currently have an island removal process which makes sure that every part of the graph is part of a component of at least size _n_. What we really need to do is make sure that all edges and vertices are members of _strong_ components, but our simple flood-fill algorithm does not work in this case.

One could argue that this is purely a data problem and should not be fixed on the R5 side, but that is also true of island removal. This is just a more general case of island removal.

**Comment by mattwigway** [comment]
Somehow OSRM makes this location work: http://www.openstreetmap.org/directions?engine=osrm_car&route=38.88826%2C-77.12739%3B38.91439%2C-77.02110#map=18/38.88833/-77.12502

However, they do not even use the closest street that is not part of a strong component, so I suspect that they're linking to multiple nearby streets. We could do that and do multi-origin Dijkstra, it would eliminate most problems like this (and maybe also much of the need for island generation). When you put the pin somewhere, it guesses what you meant by choosing the road with the most direct path to the destination, which is probably usually what is desired.

**Comment by mattwigway** [comment]
@abyrd thoughts?

**Comment by mattwigway** [comment]
I pulled out my copy of Harary, Norman and Cartwright [1] to look for a solution here. One option is to build a reachability matrix of our graph, take the elementwise product of the reachability matrix and its transposition; row _i_ of the result indicates the vertices that are in the same strong component as vertex _i_ [1, p. 123]. The trick of course is computing the reachability matrix (also known as the transitive closure) in a computationally tractable way. [Nuutilla 1995](http://www.cs.hut.fi/~enu/thesis.html) purports to do this; that algorithm relies on Tarjan's algorithm, which appears to be able to compute strong components directly, although at what computational complexity I am not sure.

[Wikipedia](https://en.wikipedia.org/wiki/Transitive_closure) also points out that the [Floyd-Warshall algorithm](https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm) can be used for computation of reachability matrices. Floyd-Warshall however has complexity O(|V|^3) which is non-ideal.

1: Harary, Frank, Robert Zane Norman, and Dorwin Cartwright. _Structural Models: An Introduction to the Theory of Directed Graphs_, New York: John Wiley and Sons, 1965.

**Comment by mattwigway** [comment]
[Tarjan's algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) appears to be a possible solution to this problem. It runs in linear time (O(|V| + |E|) which seems promising.

Other options are [Kosaraju's algorithm](https://en.wikipedia.org/wiki/Kosaraju%27s_algorithm) (which has the same complexity but Wikipedia suggests it is somewhat slower in practice) and the [path-based strong component algorithm](https://en.wikipedia.org/wiki/Path-based_strong_component_algorithm) which again has the same complexity but should perform similarly to Tarjan's algorithm.

**Comment by abyrd** [comment]
Now discussing this, seeing that these algorithms are O(|V| + |E|) we're going to just try this approach since it should get rid of disconnected islands and dead ends.

**Comment by mattwigway** [comment]
This needs to be done in advance of the next client meeting, so it should be done by March 1 to give us time for testing.
