### ISSUE TITLE
Large combined frequency and scheduled networks are slow

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#231]
Analysis is very slow on large networks consisting of combined frequency and scheduled lines, particularly when you start a trip near a headway based line - the algorithm will have to update almost all of the travel times because that headway based line is the fastest way to get just about anywhere. This kinda makes sense, however it appears that a large amount of the time is actually being spent finding the appropriate frequency entry, rather than updating the scheduled times:
```
12:38:10.840 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker - calc time 18.746sec
12:38:10.840 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -   propagation 0.0sec
12:38:10.840 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -   raptor 18.746sec
12:38:10.841 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -     scheduled 2.039
12:38:10.841 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -     frequency 16.579
12:38:10.841 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -       10.793 frequency search
12:38:10.841 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -       5.786 resulting updates to schedule search
12:38:10.841 [pool-3-thread-1] INFO  com.conveyal.r5.profile.RaptorWorker -   requested 200 monte carlo draws, ran 240
```

the 10.793 seconds is only the time that is being spent inside the conditional in RaptorWorker that checks for the presence of frequencies.

**Comment by abyrd** [comment]
Weird. At least we have a likely target for optimization.

**Comment by mattwigway** [comment]
There's a lot of looping that could be eliminated, evaluating that now.

**Comment by mattwigway** [comment]
Hmm, so the truth begins to emerge:

```RaptorWorker - calc time 15.867sec
RaptorWorker -   propagation 0.0sec
RaptorWorker -   raptor 15.867sec
RaptorWorker -     scheduled 1.54
RaptorWorker -     frequency 14.228
RaptorWorker -       9.587 frequency search exploring 901925 patterns
RaptorWorker -       4.641 resulting updates to schedule search
RaptorWorker -   requested 200 monte carlo draws, ran 240
RaptorWorker - 4 rounds
```

Note that the frequency search explores 901,925 frequency patterns. RAPTOR is supposed to explore each pattern at most once per round, and since there are 240 monte carlo draws, 4 rounds, and there are only two frequency based patterns in this graph, we should not explore frequency patterns more than 1,920 times, so we're doing approximately 469.7526042 times more work than we should be.

**Comment by mattwigway** [comment]
now the only question is why . . .

**Comment by mattwigway** [comment]
I take that back, the frequency conditional was being entered on every search but most of logic short-circuited.

**Comment by mattwigway** [comment]
So, that commit makes it 1.5 - 2x faster in the worst areas. But I have another idea that has the potential to really make it scream. In a combined network, the scheduled search is only intended as an upper bound and is never used directly, so nothing in it needs to mean anything in particular other than being an upper bound.

We used to calculate upper bounds on the combined network _for display_ by running a search with worst-case boarding time on this. We removed this as it was confusing to people, since it was an upper bound but was not tight (there's probably no way to optimize the transit network so that anyone receives the worst possible trip to every single destination). However, it would be a meaningful upper bound on the Monte Carlo search. It will be much tighter than the schedule-only bounds which use now, especially on high-frequency lines that promulgate a major increase in accessibility that are our current Achilles heel.

One might think that this wouldn't help a whole lot but I hypothesize that it would. For instance, my usual test case that brings R5 to its knees is the [Triboro RX](http://library.rpa.org/interactive/the-triboro/) in New York (I'm generous with the frequency and speed when I model this). Putting the origin near a station in one of the outer boroughs far from the remainder of the subway makes analysis slow because the Triboro accelerates almost every trip by a significant margin, because it gets you onto the remainder of the rapid transit network faster. If we are using the worst-case board time to bound, the most the improvement can be is the headway of the line*, which is likely to get sopped up by transfers before updating the travel time to every stop in the network.

The cost is that the scheduled search becomes a little slower because we explore the frequency lines on each scheduled search and cannot use range raptor as they keep moving earlier as the search progresses. I don't think this will be too slow, as its effectively just running multi-origin range RAPTOR; the arrival time at stops served by the frequency line moves back by a minute, just as it does at the origin. However, if this does turn out to be slow we could only include the frequency lines every _m_th iteration, and continue to apply range raptor, which would make the computed upper bound somewhere between the worst case boarding time and the worst case boarding time plus _m_ minutes.

I'm going to implement and see how it does.

*except when it makes sense to combine multiple frequency lines with a headway line, but that is not the slow part of the search I think assuming most of the network is unchanged.

**Comment by abyrd** [comment]
I'm going to need to re-read that to make sure I truly get the idea, but it sounds like it could work. I'm taking a look at the same part of the code to see if I can spot anything else promising.

**Comment by abyrd** [comment]
In the same block where you made the change 04e5c2c, about 20 lines lower, there's a conditional `if (inputState.bestTimes[stopIndex] != UNREACHED) {...}` that contains the frequency boarding search. This is going to be triggered constantly, not only for the reason mentioned in the comment (looking at bestTimes instead of the previous round) but because the presence of _any_ arrival at the given stop will trigger a search for a new boarding option. This means that once stops with frequency lines running through them have been touched, those frequency lines will all be boarded on every subsequent round, and re-checked for boarding at every downstream stop on the pattern.

The comment says "if already on board a vehicle we also need to check whether it's possible to board an earlier one", but that's only true if the existing arrival time at this stop improves on the stay-on-board arrival time.

I think at the very least, we want to make the search for a new boarding option conditional on `inputState.bestTimes[stopIndex]` being less than `remainOnBoardTime`, and `remainOnBoardTime` will conveniently be `Integer.MAX_VALUE` if no trip has yet been boarded.

**Comment by mattwigway** [comment]
Good catch, I'll make that change as well.

**Comment by mattwigway** [comment]
The change described by @abyrd above doesn't improve my test scenario, but I suspect it would if there were a lot of frequency lines.

**Comment by mattwigway** [comment]
It seems that in my test case my change proposed above has none-to-modest speed improvements. However, inspired by @abyrd's comments I realized that marking potential board stops touched in each round is a good idea, and seems to give a 1/3rd speed improvement or so. My code is too messy to push but I'll pick it back up on Monday.
