### ISSUE TITLE
Frequency change only works in one direction

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#235]
Marco at Movares reports that when applying a modification that is intended to change the frequency of a route in both directions, the frequency changes in only one direction, and accessibility drops to zero in the opposite direction (service seems to be removed).

This is on the Full NL network, with the scenario called ‘DR 2016 fr15min alleen ijssellijn’.

**Comment by MarcovanderLinden** [comment]
I've added a few files to help illustrate the problem. first I've added a picture of an analysis. On the left is the average accessibility with the fullNL no platforms, no shapes scenario. On the right is the average accessibility with the (also added scenario). The only thing changed in this scenario is the frequency of the train between Deventer and Zwolle. As you can see the accessibility towards Deventer improves, as expected, the accessibility towards Zwolle however, disappears completely. Somehow the line seems to be deleted in two directions. I've checked the sourcetrips and they are one in each direction. 

![change frequency](https://cloud.githubusercontent.com/assets/19469753/22926542/464dbec0-f2ad-11e6-81e5-c37c43ef496f.JPG)
[IJssellijn_DR2016 IJssellijn Freq 15min.txt](https://github.com/conveyal/r5/files/773864/IJssellijn_DR2016.IJssellijn.Freq.15min.txt)

**Comment by ansoncfit** [comment]
Not sure when this was fixed, but I just double checked that frequency modifications are properly applied in both directions.
