### ISSUE TITLE
GridResultAssembler leaves holes in output

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#252]
GridResultAssembler stops assembling regional analysis results when it has received the correct number of destinations. However, some destinations may be duplicated due to retrying from the broker or SQS (both guarantee at-least-once task delivery, not exactly-once). Thus, a regional analysis may be marked as being completed when in fact several origins have not been computed, leaving holes in the output.

**Comment by abyrd** [comment]
We have decided on this strategy: Keep a bitset of all received blocks, and upon receiving a new block only decrement the remaining blocks counter if that block hasn't been received before. As a double check, when the number of remaining blocks reaches zero, we'll set the number of remaining blocks to the number of true bits in the bitset.
