### ISSUE TITLE
Refactor / replace active pattern filtering

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#256]
In FastRaptorWorker we filter the patterns to separate them into frequency and schedule patterns, creating new lists that contain only the active patterns.

This requires six fields including some lookup tables to convert list indexes. I think these could be collapsed down to just two bitsets for active frequency and active scheduled patterns (not doing any mapping, just pre-filtering and using the original indexes). Maybe I'm missing something though. I'd also be curious to see the speed difference with no filtering at all, just to see if the complexity is worth the speedup.

This is an optimization, and one that requires maintaining index lookup tables and copying lists - do we have evidence that it provides any benefit over not filtering? Perhaps there isn't much advantage over simply making a bitset of active patterns and iterating over the set bits in that bitset to iterate over active patterns?

The original though behind the filtering was that it might get the patterns into the CPU cache, but since they're references and they probably won't all be on the same page.

**Comment by ansoncfit** [comment]
Closed by #708.
