### ISSUE TITLE
Removing irrelevant trips causes changes in travel time

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#26]
When working on #3 I made a filter that removes all trips whose service IDs are not active, and which are outside the time search time window. Removing these trips that theoretically have zero effect on the search caused small (1-10 minutes) but definite changes in travel time to areas far away from the origin point.

**Comment by abyrd** [comment]
One possible culprit was the fact that such "irrelevant" trips were removed entirely, making the list of TripSchedules within certain TripPatterns shorter, and if all trips were removed from a TripPattern that pattern itself might be removed, which amounts to re-numbering the TripPatterns. This means the TripPatterns must be re-indexed after the filtering operation, but this was being done. I did discover though that zeroing out TripSchedules instead of removing them from their TripPatterns eliminated the travel time discrepancies. Retaining irrelevant trips whose final arrival time was just before the search time window also alleviated (but did not eliminate) the problem. This seems to be an error where the first trip in a pattern is not being considered, and inserting an extra irrelevant pattern moves that first pattern into a position where it's considered.

This does appear to be the case: in the RAPTOR algorithm there is a step where we scan backward trip by trip to see if there are any earlier trips that can be boarded from a particular stop. That process is stopping at trip 1 rather than trip 0.

**Comment by abyrd** [comment]
Seems to be resolved. Closing.

**Comment by abyrd** [comment]
Unfortunately there are still much smaller differences in cumulative accessibility way out near the limits. Removing the time-based (as opposed to service ID based) trip filtering seems to eliminate this difference. Re-opening the ticket until I figure out what's causing this.

**Comment by abyrd** [comment]
I am currently unable to reproduce the small differences in cumulative accessibility mentioned above. I'm wondering if I had some bad responses hanging around in my browser cache. Leaving this ticket open for later verification.

**Comment by mattwigway** [comment]
@abyrd: is this still an issue?

**Comment by abyrd** [comment]
Will need to re-check. My last impression was that I was only seeing problems due to stale cache.
