### ISSUE TITLE
Quieter zero-length hop log messages

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#271]
Loading the Netherlands data logs thousands of messages like: "Zero-length hop at stop 654111 on trip 52881026 on route 41868 9". We need to understand why there are so many zero-length movements in the stop times, and either silence these warnings when the zero-length hops are intentional, or clean the data to remove these zero-length hops. @skinkie can you help us understand this characteristic of the data?

**Comment by skinkie** [comment]
More debug data required. Dump some stoptimes, stops, etc.

**Comment by ansoncfit** [comment]
There are plenty of zero-duration hops (arrival time = previous departure time, according to https://github.com/conveyal/r5/blob/77c41bdf94f7c97af7ebb4f289cce82dd7dd315d/src/main/java/com/conveyal/r5/transit/TransitLayer.java#L251  
) in the stock MBTA feed.

For example, Route 91 seems to enjoy teleportation on Prospect and Springfield Streets.
```
34978745,06:50:00,06:50:00,1060,1,,0,1,1,cntsq
34978745,06:50:00,06:50:00,2446,2,,0,0,0,
34978745,06:51:00,06:51:00,2447,3,,0,0,0,
34978745,06:51:00,06:51:00,2448,4,,0,0,0,
34978745,06:51:00,06:51:00,2449,5,,0,0,0,
34978745,06:52:00,06:52:00,2451,6,,0,0,0,inman
34978745,06:53:00,06:53:00,2768,7,,0,0,0,
34978745,06:53:00,06:53:00,2769,8,,0,0,0,
34978745,06:54:00,06:54:00,2530,10,,0,0,0,
34978745,06:54:00,06:54:00,2770,9,,0,0,0,
34978745,06:55:00,06:55:00,2597,11,,0,0,0,unsqu
34978745,06:56:00,06:56:00,2773,12,,0,0,0,
34978745,06:56:00,06:56:00,2774,13,,0,0,0,
34978745,06:57:00,06:57:00,2775,14,,0,0,0,
34978745,06:57:00,06:57:00,2776,15,,0,0,0,
34978745,06:58:00,06:58:00,2778,16,,0,0,0,
34978745,06:59:00,06:59:00,2777,17,,0,0,0,
34978745,06:59:00,06:59:00,2779,18,,0,0,0,
34978745,07:01:00,07:01:00,2874,19,,1,0,0,sull
```
![image](https://user-images.githubusercontent.com/2173529/31142470-63605616-a848-11e7-8f23-ff4b2d53cc2f.png)

**Comment by landonreed** [comment]
Teleportation, wormholes, time travel.  Who knows what that bus has got under the hood...
