### ISSUE TITLE
Make number of transport networks in TransportNetworkCache configurable

### ISSUE THREAD

**Issue by landonreed** [conveyal/r5#279]
Currently [TransportNetworkCache.java](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java) supports only one transport network.  When using r5 as a library (e.g., conveyal/datatools-server) we need support for multiple transport networks.  Perhaps the behavior should follow that of [BaseGTFSCache](https://github.com/conveyal/gtfs-lib/blob/master/src/main/java/com/conveyal/gtfs/BaseGTFSCache.java) and just accept as many networks as memory allows.

**Comment by abyrd** [comment]
Even within Analysis workers we'll eventually want it to cache multiple networks. This is why the network cache interface exists, even though the actual implementation just holds on to the last network used.

However, it seems to me that many tasks we want to perform should be performed in isolation, i.e. completely separate R5 instances should be created, then tasks performed in sequence to limit memory consumption, much as we do with other tasks that are fed through the worker thread pool. In that case each R5 worker would only see one graph.

But maybe I'm not aware of the use case you're building for.

**Comment by abyrd** [comment]
Also, unfortunately it's basically impossible within a JVM to fully understand how much memory you've got, and what the full memory cost of an object tree is.

**Comment by landonreed** [comment]
This was addressed in #281 with the use of a loading cache and a configurable number of networks to cache (defaults to 1).
