### ISSUE TITLE
Origin and destination linked to same edge does not work

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#287]
Consider a case where there is a long edge with no intersections. In analysis, placing the origin on this edge will create a sample that is linked to the ends of that edge. Reaching any destinations along that edge will require the router to walk to the end of the edge and back, causing an unrealistic drop in accessibility in the middle of the edge, as evidenced by the isochrone below:

![image](https://user-images.githubusercontent.com/566958/27464981-13b0b218-5803-11e7-9c5d-2a6d7cf9729d.png)

**Comment by mattwigway** [comment]
Per discussion with @abyrd, we can fix this by having a special case where destinations that are linked to the same edge as the origin get special treatment (basically just looking at where they are linked on the edge relative to the origin and applying the walk speed.

**Comment by ansoncfit** [comment]
We decided not to address this nuance a while ago, because it generally does not affect results for cumulative opportunity results with cutoffs longer than the time needed to traverse the edge. But as we roll out gravity decay measures more widely, we should prioritize.
