### ISSUE TITLE
Install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by Robinlovelace** [conveyal/r5#289]
Roughly reproducible example:

```bash
cd ~/Programs/r5-2.3.0/src/main/java/com/conveyal/r5
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get install oracle-java8-installer
javac R5Main.java

# R5Main.java:3: error: package com.conveyal.r5.analyst.broker does not exist

```

Could help document install if that would help (could not find it but maybe I'm not looking hard enough!).

**Comment by abyrd** [comment]
Hi, R5 is a Maven project. The build instructions are in `pom.xml`. You'll need to install Maven and use that to build R5, rather than calling javac directly.

**Comment by Robinlovelace** [comment]
Ah OK. Is this documented other than in this thread? Would be beneficial for reproducibility of people using r5 if so.

**Comment by abyrd** [comment]
@Robinlovelace at this time there's not a community around R5, it's mostly an internal library used at Conveyal. We don't have the time to devote to managing a real community now, so haven't created much in the way of documentation. However it's true that we should at the very least tell people how to build the software - I'll add that section to the readme.

**Comment by Robinlovelace** [comment]
OK many thanks for that, and creating what seems like a very important piece of software. Tech like this could help in the transition away from fossil fuels, especially because it's open and leads to collaboration, as advocated by [Macron](https://twitter.com/emmanuelmacron/status/870404412304482304?lang=es).

Communities have pros and can help in some ways, especially with testing and documentation: people like @rafapereirabr, @VeetVoojagig, myself and others could be well suited for stuff like this (no promises - I only mention those guys as we have discussed this project loosely a few weeks ago).

Thanks again for the work on this.
