### ISSUE TITLE
Multiple board stops

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#29]
We frequently have many possible places to board a single line:
![image](https://cloud.githubusercontent.com/assets/566958/11410782/4b46a5b0-9398-11e5-8b1a-cceef68525db.png)

The reason for this is pretty clear. Suppose that you have a 20-minute walk limit to transit and can reach 3 stops on a given line:

![image](https://cloud.githubusercontent.com/assets/566958/11410831/b19ec5b8-9398-11e5-89cc-c18fa3b6062b.png)

Obviously stop 2 is the closest, but most of the time the router will board at stop 1 because it's earlier on the trip and thus is reached first, and usually it doesn't matter which stop you go to as you'll wait there a while anyhow and catch the same vehicle. However, occasionally walking to stop 1 means you just miss a vehicle, so the router will board the earlier vehicle at stop 2. So both paths are present in the output.

Depending on the differences in path lengths and the relative speed of the vehicles, it might occasionally make sense to walk to stop 3 so you can just catch a vehicle you would otherwise have missed at stop 2.

There's no easy heuristic solution; you don't always want to board at the first stop you reach, nor at the last (in fact, the situation here is common enough, with a vehicle running in a straight line, that frequently you will want to board somewhere in the middle).

I think the right solution is to have another array in RaptorState that has the walk distance/time. We don't need to add it to the Pareto front (that would make computation much slower), we just need to use it as a tiebreaker when optimizing on travel time.

**Comment by mattwigway** [comment]
Hmm, this gets messy given that we're also using number of transfers as a tiebreaker. The easy way I just described to implement this will yield inconsistent results, with lower-walk but more-transfer results being found and propagated from in later rounds. I have to flesh this out in my mind to describe the exact problem, but leaving this here so I remember the sinking feeling I have now about this approach on the other side of Thanksgiving dinner.

**Comment by abyrd** [comment]
We could probably devise a way to force boarding each pattern at the closest stop on that pattern after any walk/transfer step.

**Comment by mattwigway** [comment]
In a scheduled network this shouldn't be a problem. Range RAPTOR is stepping backwards in time so it will find the quickest trip first and shouldn't replace it with the same trip boarded at a different stop as it continues to move backwards in time. The "fix" I proposed above would actually make the situation worse.

Note that the word should above is used in the form that indicates an ideal state, not what I believe is actually happening. The screenshot above comes from a scheduled network, so clearly this is not working as intended.

**Comment by mattwigway** [comment]
This is probably fixed (it would be obvious in modeify).
