### ISSUE TITLE
FastRaptorRouter searches on schedule-only networks artificially deflated

### ISSUE THREAD

**Issue by landonreed** [conveyal/r5#306]
For `GridComputer` searches on schedule-only networks, regional accessibility results appear to be significantly deflated relative to networks with frequency modifications.  For example, a network with a single 'add trip' and 'reroute' modification produced the following result:

![image](https://user-images.githubusercontent.com/2370911/28228186-63ec7556-68ab-11e7-815f-8eb94a843947.png)

@mattwigway suggests duplicating schedule search results (multiplying by number of Monte Carlo draws per minute used by frequency search) in order to bolster results relative to networks with frequencies.

**Comment by mattwigway** [comment]
Fixed in v2.3.1
