### ISSUE TITLE
Routes with no trips cause failure when applying adjust-speed to all routes

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#314]
It seems that almost every GTFS feed has at least a route or two that have no trips. When using the "Apply to All Routes" option in the frontend, these routes are included in the modification sent to the backend and to R5, which causes a scenario application error because it checks for the presence of trips on those routes. Instead, we should check for the presence of the routes themselves, if any are missing throw an error. If any routes have no trips found, this should be a scenario application warning (which will also be displayed in the UI but will not block analysis).

**Comment by abyrd** [comment]
This is particularly bad in NYC, where each of the five boroughs has a bus feed, and each of these bus feeds contains all the bus routes, but only contains stop times for the routes in one borough. Most of the routes are empty in all these feeds.
