### ISSUE TITLE
Faster algorithm for rasterizing polygons

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#315]
We currently intersect every pixel geometry (rectangular polygon) within the bounding box with each polygon when rasterizing polygons into a grid. This is too slow.

**Comment by ansoncfit** [comment]
@abyrd and I discussed this again today. 

When loading a shapefile as large as the UK, the staging server does not have enough memory to cope.

There's [more work](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/analyst/Grid.java#L138) to do to "avoid duplicating expensive geometric math."

**Comment by ansoncfit** [comment]
Amending the above.  In July, the staging server showed high CPU utilization when three users attempted to set up Analysis regions and upload shapefiles, including one for the UK.  I'm not sure that there was "not enough memory to cope."

**Comment by ansoncfit** [comment]
Addressed in https://github.com/conveyal/r5/pull/350
