### ISSUE TITLE
Jobs are never purged from broker

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#318]
It looks like jobs just accumulate in the broker even when they're finished. I currently see 24 jobs on the broker, only one of which has any work remaining. Assuming these objects hold on to their constituent task objects, this could be a major memory leak.

**Comment by abyrd** [comment]
I think the reason jobs are not purged is that the front end needs to display job progress, and I wasn't quite sure whether removing the job from the broker would leave the UI in a confused state. However, it appears that the UI is reporting the state of the grid assemblers on the backend, never looking directly at the broker jobs. This is also why the UI progress often lags behind the broker's reported progress on a given job: the UI is reporting how many tasks the grid assembler has pulled off the SQS queue and slotted into place, not how many tasks have been reported completed by the workers.

**Comment by abyrd** [comment]
Note that with the fix in 2f043a1 we're only purging jobs that complete. A stalled job will still eat memory, so we need a scavenger that occasionally detects and removes those if they exist.

**Comment by ansoncfit** [comment]
See https://github.com/conveyal/analysis-ui/issues/405
