### ISSUE TITLE
Broker stores millions of near-identical task objects

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#320]
For a regional job, the broker will store hundreds of thousands or millions of task objects that are identical except that each one has different origin point coordinates. We really only need to store one object and a list of coordinates, or one object and a reference to the pointset that can generate the coordinates. Then the finished/in-progress/etc. are just BitSets of indexes into the PointSet.

The current system uses gigabytes of memory just storing all these repetitive objects.

**Comment by ansoncfit** [comment]
The current approach becomes particularly untenable when applying reroute modifications to routes with many trips.  A single-point request for a modest scenario I created (with six reroute modifications) ended up being 155 kB, which does scale well when storing the same scenario 1 million times.
