### ISSUE TITLE
Unexpected Island Pruning for SF Bay Bridge

### ISSUE THREAD

**Issue by colinsheppard** [conveyal/r5#335]
Hi there, we are using R5 on a subset of the San Francisco OSM network that includes the financial district, and some of the Bay Bridge including Treasure Island.

When we build the R5 network, the TarjanIslandPruner removes the Bay Bridge along with the motorway links through the city all the way up until the surface streets. See attached image where red indicates the links that have been pruned.

![image](https://user-images.githubusercontent.com/333206/30036835-5d0e872c-916b-11e7-8e6e-a9e6d687b2d7.png)

I've confirmed that during execution of the Tarjan algorithm, the links in red appear to be identified as 1-vertex strong components. 

I understand that 1-way dead ends get pruned, so it would make sense if the bridge where to be pruned on the edge of the area of detail, but not consistently throughout the entire bridge/highway system as there are multiple on-ramps and off-ramps which would form a graph cycle from any interior point on the highway to any other.

In fact, because we used completeRelations=true during clipping of the network, the actual network being proceed by R5 extends far beyond the area of detail (see second attached image) so there are even more opportunities for cycles.

![image](https://user-images.githubusercontent.com/333206/30036842-6c7ca950-916b-11e7-994e-b52efa008d4d.png)

Do you have any idea how these links could be getting pruned and how we can fix the issue?

Thanks.

**Comment by colinsheppard** [comment]
In case you want to recreate our situation, here is the data we are using:

https://www.dropbox.com/s/44fnvl9n25la74w/sf-detail.osm.pbf?dl=0
https://www.dropbox.com/s/undir2ox84wv6ka/SF.gtfs.zip?dl=0

**Comment by ansoncfit** [comment]
Part of this issue relates to `minComponentSize`.  Setting `MIN_SUBGRAPH_SIZE = 3` in r5/streets/StreetLayer allows pedestrian routing on Treasure Island and car routing across to SF:

![image](https://user-images.githubusercontent.com/2173529/31829217-a2ef3924-b58a-11e7-86aa-2c20038f89af.png)

![image](https://user-images.githubusercontent.com/2173529/31829256-bc029244-b58a-11e7-90c2-ebed06b90884.png)

But there are still problems.  Note the "island" around 9th/Folsom in the above, and the fact that car routing does not work from SF to Treasure Island:

![image](https://user-images.githubusercontent.com/2173529/31829410-28f43f24-b58b-11e7-9b84-cdd7100b6675.png)

When setting `MIN_SUBGRAPH_SIZE` back to the default (40), there is still a smaller island pruned out around 9th/Folsom:

![image](https://user-images.githubusercontent.com/2173529/31829735-2faa9182-b58c-11e7-8220-8e7c74b5fab6.png)

Tagging the end of Gordon St. as a turning circle might fix this issue, but I don't think it matches ground truth:
![image](https://user-images.githubusercontent.com/2173529/31830121-47e1fba4-b58d-11e7-8cd4-3167a99ad28a.png)


![image](https://user-images.githubusercontent.com/2173529/31830142-571e6c88-b58d-11e7-994a-c820e080cbc9.png)

**Comment by colinsheppard** [comment]
Thanks for looking into this @ansoncfit. I'd consider Gordon St. a legitimate case for a turning circle since those vehicles obviously don't just sit there stuck facing the wall but do 3-pt turns to get out of there. In fact, it might even be legitimate to turn such a situation into the rule rather than the exception... dead ends always allow for turning around.

So when min_subgraph_size is 3, how does that prevent the pruning of the ramps and highway edges which are being identified as 1-vertex components? It's great if it works, but I'm confused about how.

**Comment by ansoncfit** [comment]
@colinsheppard Looking more closely at the Gordon St. example, I would support adding the Turning Circle tag to that node in OSM.  The degraded curb on the left essentially makes the sidewalk part of "a widened area of road that allows vehicles to turn more easily."

Regarding the more important issue, I'm still looking through StreetLayer and Split.

**Comment by ansoncfit** [comment]
Some more examples of streets missing car permissions:

![image](https://user-images.githubusercontent.com/2173529/32453392-0f3a3c3e-c2ea-11e7-9922-6646a874eb06.png)

**Comment by ansoncfit** [comment]
More unexpected disconnections, this time in Southern California:

![image](https://user-images.githubusercontent.com/2173529/32467160-9e17dae2-c317-11e7-978c-a9157aca6cf9.png)

**Comment by ansoncfit** [comment]
More notes on diagnosing what we think may be a forward/backward edge issue.

Check logic here:
https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/streets/EdgeStore.java#L442, and cf. copyPairFlagsAndSpeeds
A above in EdgeStore notes: "There are separate flags and speeds entries for the forward and backward edges in each pair."  

Do we need a forward/backward check in [forEachOutgoingEdge](https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/streets/TarjanIslandPruner.java#L277)?

**Comment by abyrd** [comment]
More possibly relevant evidence uncovered: near Amsterdam north of the IJ there are several cells that appear to be linked in such a way that they are inaccessible. They are in the middle of a highway, but we are specifically linking for walking.

![image](https://user-images.githubusercontent.com/112871/32891528-230b2ef8-cad3-11e7-8e6e-30bb7469f2fc.png)
