### ISSUE TITLE
do not link water to roads with zero cost

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#337]
It seems like we're still linking faraway cells to roads with minimal or no cost. This should be changed with a shorter linking distance and lower speed to traverse any >1 cell links.

**Comment by abyrd** [comment]
We appear to still have this problem wiith driving searches. There are still big horizontal jumps in isochrones at the coastline (see image) which imply zero travel time. ![image](https://user-images.githubusercontent.com/112871/39625287-0c59af78-4f9d-11e8-9409-c3e4b8718e19.png)

**Comment by abyrd** [comment]
This might just be an illusion caused by the car being relatively fast. Still should be checked in the code to make sure speed is being properly applied.

**Comment by ansoncfit** [comment]
We are applying a cost: https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/streets/LinkedPointSet.java#L320

For cars, the assumed speed is 11 m/s (https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/profile/ProfileRequest.java#L66), which takes one pretty far into the water in 60 seconds. 🌊 

Other than linking pointset points to streets, it looks like the only other place `carSpeed` might be used is the StreetRouter's A* heuristic.  So we could consider reducing it to something closer to real driveway/parking lot speeds.

**Comment by ansoncfit** [comment]
:tada: This issue has been resolved in version 4.2.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
