### ISSUE TITLE
How to add pedestrian permissions on street with sidewalks?

### ISSUE THREAD

**Issue by buma** [conveyal/r5#34]
I'm improving permission support and I would like to know how would we want to support sidewalks.
For example street with sidewalks can have three types of sidewalk tags:
- sidewalk:left
- sidewalk:right
- sidewalk:both
- sidewalk:none

Should street get pedestrian permissions in all first three cases in both direction since pedestrian permission usually doesn't obey oneways or should we add pedestrian permissions only in direction it is given. (`right` for forward edge, `left` for backward edge `both` for both).
Bicycle permissions obey direction (cycleway:left=lane, cycleway:right=track etc) because cycling also obeys one ways.

**Comment by mattwigway** [comment]
Yes, your analysis is correct. OSM also has provision for one way pedestrian streets which can be handled separately (or not at all, they're extremely uncommon outdoors).
