### ISSUE TITLE
Bike has zero accessibility in most places

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#349]
In places where walk+transit produces reasonable results, bike+transit does not. You get reasonable accessibility figures in a few scattered locations, but zero accessibility in most locations.

![image](https://user-images.githubusercontent.com/112871/31353083-2223bc5e-acff-11e7-85de-175a0b9f67a2.png)

![image](https://user-images.githubusercontent.com/112871/31353099-30a8b806-acff-11e7-9d8c-0b1aa7a26cfb.png)

**Comment by ansoncfit** [comment]
Biking works as expected as a direct mode (i.e. with transit turned off):
![image](https://user-images.githubusercontent.com/2173529/32304007-8c9d3722-bf42-11e7-9614-42ee41c64b99.png)
(from the linking-fixes branch)

But not as an access mode:
![image](https://user-images.githubusercontent.com/2173529/32304074-ea96019c-bf42-11e7-88d8-e2dd1bf86c4c.png)

**Comment by ansoncfit** [comment]
This expects a biking access limit in seconds:
https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java#L157

But our default request has `maxBikeTime: 20` (presumably minutes, or we've got some lazy bike riders)

Multiplying by 60 at the line above should fix the issue.
