### ISSUE TITLE
Teleportation for walk-only trips

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#360]
Note the small area of reachability near Little Nahant (northeast quadrant):

![image](https://user-images.githubusercontent.com/2173529/32462126-47936ea4-c306-11e7-8462-df824b8a29d1.png)

![image](https://user-images.githubusercontent.com/2173529/32462140-579228c2-c306-11e7-945d-891be8d8b76d.png)

Is an int overflowing somewhere?

**Comment by ansoncfit** [comment]
The erroneously reachable areas seem to be near the borders of graphs.

A possibly related example, west of Portland:

![image](https://user-images.githubusercontent.com/2173529/34902070-0db6d368-f7e2-11e7-8ba9-8cde03e9d652.png)


![image](https://user-images.githubusercontent.com/2173529/34902069-00bf944c-f7e2-11e7-8fe6-4d5da82a1364.png)

**Comment by ansoncfit** [comment]
Linking also seems suspect.  

Reasonable:
![image](https://user-images.githubusercontent.com/2173529/34902159-da37c77a-f7e3-11e7-81be-c09f95df0260.png)

Questionable:
![image](https://user-images.githubusercontent.com/2173529/34902165-02d8209e-f7e4-11e7-91c9-7cd37bfb28ee.png)

**Comment by ansoncfit** [comment]
Starting from the middle of a racetrack:
![image](https://user-images.githubusercontent.com/2173529/34902187-52737662-f7e4-11e7-8716-8abb13a8296b.png)

**Comment by ansoncfit** [comment]
These latest examples may be unrelated to the original issue.  But Marco has reported something resembling the original issue for bikes:

![image](https://user-images.githubusercontent.com/2173529/34902522-1e4fd64e-f7eb-11e7-9982-c0559370ba54.png)

**Comment by abyrd** [comment]
@ansoncfit your original image and Marco's do look like they could be overflow. Since in the UI we use single bytes for travel times in minutes, anything over about 2 hours is subject to overflow so maybe we should add some additional checks.

**Comment by ansoncfit** [comment]
The Portland International Raceway examples above (not int overflow issues) can be addressed with the FIXME here: https://github.com/conveyal/r5/blob/701916ee71d9f51f7115118569c648370e52bff2/src/main/java/com/conveyal/r5/streets/StreetRouter.java#L324.  The time to reach the two vertices of an origin split edge is not set, so both ends can be reached in 0 travel time (teleportation!)
