### ISSUE TITLE
Hard to tell when jobs are truly finished

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#380]
Tasks within a job are checked off (from the broker's point of view) when the worker says the task is complete. However the worker then puts the result into an SQS queue, and the job is not actually done until all those results are consumed and inserted into the final result file by another component. This means that the broker may report a job is complete (workers have finished all tasks) when there are still results waiting in that queue. If we were to restart the backend at that time, the results would never be completely assembled and uploaded to S3 even though all results had made it into the queue.

I think this has already happened a few times causing us to trash large amounts of completed work. Really we should just not have two different ideas of "complete". The task should be considered complete when the backend inserts the result into the final result file, not when the worker delivers the result. The worker could even deliver results synchronously, with the API call that delivers the result blocking until it is inserted into the final result. That might decrease worker efficiency though, since workers could end up waiting for the backend to catch up with them.

**Comment by abyrd** [comment]
In the new broker design, this is handled by workers returning work results directly to the back-end. The results are slotted into the results file immediately upon reception, before the corresponding tasks are marked as complete. So when all tasks in a job are marked complete, the results file is also complete. It appears that the results queue was just a workaround for slow disk IO.

**Comment by ansoncfit** [comment]
This was resolved a while ago; see `isComplete()` and `verifyComplete()` in Job.

We did recently see something that might have been the reverse of this -- a task being handled after the corresponding result file was closed:

```
java.io.IOException: Stream Closed
at java.base/java.io.RandomAccessFile.seek0(Native Method)
at com.conveyal.analysis.results.GridResultWriter.writeOneOrigin(GridResultWriter.java:145)
```

Occasional delivery of tasks to closed result writers, whether due to the job being deleted or marked complete after certain tasks were sent in a redelivery round, is not concerning but we should open a new issue if we this starts appearing often.
