### ISSUE TITLE
Workers seem to run out of memory due to multiple scenarios

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#382]
After a worker is on for many days sometimes it will grind to a halt, and the worker list shows that it has a lot of scenarios loaded. Perhaps we are holding on to too many scenarios, but those should be small. What are the scenarios holding on to that exhausts memory? Somehow holding onto linkages?

**Comment by ansoncfit** [comment]
Scenario and linkage caching has been revised recently. Furthermore, workers are rarely on for many days now that auto-startup is in place.
