### ISSUE TITLE
Allow task push to workers

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#384]
We have two different ways of handling analysis tasks : synchronously (used for single origin point travel time surfaces) and asynchronously (used for batches of regional accessibility analyses). The latter determined the overall architecture of the system with workers always pulling tasks from the broker. However, traditionally the synchronous requests would be handled by pushing the tasks to a pool of workers (like a load balancer across several identical web servers). We might even eventually want to switch to using a stock load balancer for single point synchronous requests (though it would need some capability for categories of workers with already-loaded networks).

Either way, the worker should have an HTTP endpoint where it can receive pushed requests for immediate handling, returning the serialized result back over the same connection. The underlying non-http (Java) method should also be exposed, for possible use in a local system without a load balancer / reverse proxy.

**Comment by ansoncfit** [comment]
Addressed in #399.
