### ISSUE TITLE
Add trip modifications not reflected in results

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#385]
Here's an add trip modification working as expected with commit `1bf05ee`:

![image](https://user-images.githubusercontent.com/2173529/33912987-fc579a10-df65-11e7-8ad3-bfca1ffab6af.png)

The same comparison with commit `aebf4fb`:
![image](https://user-images.githubusercontent.com/2173529/33913012-13dedf54-df66-11e7-868c-0688274f2929.png)

This bug may have been introduced in recent linking fixes.

**Comment by abyrd** [comment]
Looks like `1bf05ee` is current `HEAD` of `master`, and `aebf4fb` is current `HEAD` of `dev`. There are several intervening commits - do we actually have any evidence as to which one caused the problem? This might also have to do with changes to scenario caching. We will need to see any errors generated by the scenario application process (on the worker). Those should mostly be passed back for display in the UI. Does the UI show any scenario application errors or analysis errors?

**Comment by ansoncfit** [comment]
No errors or warnings show up in the UI.

Expected results from a sample scenario in Louisville:

![image](https://user-images.githubusercontent.com/2173529/34010236-ebbbcc74-e0d9-11e7-93cc-09bf45b428c1.png)

Log for a `1bf0533` worker, which recalculates distances to street vertices from **1404** stops:
```
9262 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Finding distances from transit stops to street vertices.
9263 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Selectively finding distances for only those stops potentially affected by scenario application.
12751 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Done. Computed distances to street vertices from 1404 of 4497 transit stops.
12752 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransferFinder - Finding transfers through the street network from 10 stops...
12782 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransferFinder - Done finding transfers. 0 stops are unlinked.
12782 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Linking pointset to street network...
12782 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Linking a subset of points and copying other linkages from base layer
12851 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Done. Linked 5 of 66975 PointSet points to streets.
12851 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - 30973 points are not linked to the street network.
12851 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Creating distance tables from each transit stop to PointSet points.
12968 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Selectively computing tables for only those stops that might be affected by the scenario.
13612 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Done. Computed distances to PointSet points from 1404 of 4497 transit stops.
13612 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransportNetworkCache - Done applying scenario. Caching the resulting network.
```


Log for a `aebf4fb` worker, which recalculates distances to street vertices from **0** stops:
```
5718 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Finding distances from transit stops to street vertices.
5718 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Selectively finding distances for only those stops potentially affected by scenario application.
5743 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransitLayer - Done. Computed distances to street vertices from 0 of 4487 transit stops.
5744 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransferFinder - Finding transfers through the street network from 0 stops...
5744 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransferFinder - Done finding transfers. 0 stops are unlinked.
5744 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Linking pointset to street network...
5744 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Linking a subset of points and copying other linkages from base layer
5768 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Done. Linked 0 of 66975 PointSet points to streets.
5768 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - 30973 points are not linked to the street network.
5768 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Creating distance tables from each transit stop to PointSet points.
5904 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Selectively computing tables for only those stops that might be affected by the scenario.
5911 [pool-1-thread-1] INFO com.conveyal.r5.streets.LinkedPointSet - Done. Computed distances to PointSet points from 0 of 4487 transit stops.
5911 [pool-1-thread-1] INFO com.conveyal.r5.transit.TransportNetworkCache - Done applying scenario. Caching the resulting network.
```

But the isochrone results are the same (i.e. the bug does not appear to affect this case).

The Atlanta and Sydney examples where this issue is present have add-trip modifications with exactTimes = false, whereas the Louisville example has exactTimes = true.   

I'll look into this more.

**Comment by ansoncfit** [comment]
using `aebf4fb`

exactTimes = false:
![image](https://user-images.githubusercontent.com/2173529/34012475-e2a9c610-e0e1-11e7-89a7-3f542d790ebc.png)


exactTimes = true:
![image](https://user-images.githubusercontent.com/2173529/34012498-0174560a-e0e2-11e7-84be-bf49d50e1465.png)

Next step: pausing execution after applying add-trip modifications and checking that the timetables are sensible.

**Comment by ansoncfit** [comment]
The issue was introduced here: https://github.com/conveyal/r5/pull/369

An add-trips modification with exactTimes = false (i.e. that has frequencies) does not set transit.hasFrequencies to true.
