### ISSUE TITLE
Reverse optimization

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#39]
We don't need it for Analyst, but for static site generation/modeify use we need to be able to reverse optimize trips. We can do this at the target stop level for now because the rest will be handled in the client.

**Comment by mattwigway** [comment]
Agh this gets really messy. Consider these two examples, both of which suggest a solution that won't work with the other.

1) You can ride to stop B now or wait five minutes and ride to stop B. If you wait, you miss your transfer to destination 1 but not destination 2. Thus if you're going to destination 2 you should wait, if you're going to destination 1 you shouldn't. The obvious solution is to just keep moving forward in time, using the RaptorState from the next minute, until you find one that doesn't arrive at the same time.
2) However, that breaks when you have frequency-based routes, which will have different random offsets in each iteration.

**Comment by abyrd** [comment]
I'd rather avoid any hacks even remotely resembling "reverse optimization". I think the only really defensible thing to do is to reverse all the paths found one by one, by actually doing a backward search. Considering how tight the constraints are (derived from the forward results), it might be acceptably fast. We'll need this capability for point to point trip planning searches anyway.

We will at some point need to consider/include suboptimal options for Modeify too.

**Comment by mattwigway** [comment]
We also don't need this for schedule-based networks, see #42.
