### ISSUE TITLE
running regional analysis with limited extent affects subsequent single point requests

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#394]
I ran a regional analysis with a very small geographic extent. Since then all single point requests on the same scenario return results that only cover the extent selected for the regional analysis.
```
18:30:59.689 [pool-1-thread-6] INFO  c.c.r5.transit.TransportNetworkCache - Reusing cached TransportNetwork for scenario 5a3416a732b6b04f916d526c-0-223132457.
```
This may be because I set it to produce a static site, so regional analysis tasks are running the travel time surface propagator rather than the accessibility propagator. There may be assumptions in that travel time surface propagator code that we're always producing travel times to the entire 

Indeed even when doing a regional analysis for a limited extent of origins, we want to reach all the destination cells in the region, not just those that are origins.

**Comment by abyrd** [comment]
Whoa, this persists after I restart the backend. It actually appears that this is caused by the "bounds of analysis" setting in the UI rather than the previously run regional analysis.

**Comment by abyrd** [comment]
With a little distance, I now realize that this is intentional. Setting the bounds now affects both single-point and regional analyses, and affects both the origin and destination grids for regional analyses. This is not what most users want, and the meaning of the setting is ambiguous. We need to make it clearer what this means, and allow separate origin and destination grids in regional requests.

**Comment by ansoncfit** [comment]
Separate origins and destinations in regional requests are now allowed (introduced in #529, I think), and the user manual was updated in https://github.com/conveyal/docs/pull/62
