### ISSUE TITLE
Frequency support is broken

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#40]
After running a search on a frequency-based network I get paths that have 30+ components. Obviously there's something wrong here.

**Comment by mattwigway** [comment]
Upon closer inspection, it appears that this problem only occurs for the best-case paths. Of course one would expect more rounds when computing the best-case travel time but this is ridiculous.

**Comment by mattwigway** [comment]
And we'll also need to make sure averaging works correctly, see opentripplanner/OpenTripPlanner#2164

**Comment by mattwigway** [comment]
Looks like this is an issue with negative cycles, oops:
```
14:50:14.569 [qtp1662157298-24] ERROR com.conveyal.r5.profile.RaptorWorker - Negative speed travel, path dump follows:
Stop  2879 at 33387, reached by pattern     6 from stop  2702
Stop  2446 at 34901, reached by pattern    79 from stop  1529
Stop  2551 at 32816, reached by pattern    30 from stop  1568
Stop  1503 at 32948, reached by pattern    23 from stop  3016
Stop  2551 at 30737, reached by pattern    30 from stop  1379
Stop  1503 at 30869, reached by pattern    23 from stop  3016
Stop  2551 at 28658, reached by pattern    30 from stop  1379
Stop  1503 at 28790, reached by pattern    23 from stop  3016
Stop  2551 at 26579, reached by pattern    30 from stop  1379
Stop  1503 at 26711, reached by pattern    23 from stop  3016
Stop  2551 at 24500, reached by pattern    30 from stop  1379
Stop  1364 at 24636, reached by pattern    65 from stop  2647
Stop  2827 at 24806, reached by pattern    51 from stop  1624
```

**Comment by abyrd** [comment]
Time for some of those assertions we were talking about earlier.

**Comment by mattwigway** [comment]
OK, it appears the input data I had had trips that travel backwards in time. Oops.

**Comment by mattwigway** [comment]
That looks much healthier:

![image](https://cloud.githubusercontent.com/assets/566958/11697956/5bdac364-9e8a-11e5-8529-369e33b4f1ea.png)
