### ISSUE TITLE
Split currently splits closest edge if edge doesn't have correct permissions path isn't found

### ISSUE THREAD

**Issue by buma** [conveyal/r5#41]
We need to add support for edge splitter (`Split` class) to support permissions. One way is to add mode parameter. But I'm not sure what mode is used in:
- TemporaryStop
- LinkedPointSet
- getOrCreateVertex aka associateStops

Is this always walking or can be anything else too?

**Comment by mattwigway** [comment]
I think it's fine to have it always be walking for TemporaryStops and associateStops. You will never drive all the way to a transit stop, and you can always walk your bike to reach a transit stop. The LinkedPointSet is more complicated, and depends on the use; sometimes you will want to use LinkedPointSets with driving.

**Comment by buma** [comment]
So for LinkedPointSets we need to somehow add mode to it. So then we can use split with correct mode Walking or Driving.

**Comment by mattwigway** [comment]
Yes, I think that's what we have to do.

On Fri, Dec 11, 2015 at 10:42 AM, Marko Burjek <notifications@github.com>
wrote:

> So for LinkedPointSets we need to somehow add mode to it. So then we can
> use split with correct mode Walking or Driving.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/41#issuecomment-163967485>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by buma** [comment]
I wanted to changed getOrCreateVertex to use specific mode or get mode as an argument for splitting edges. It is called from applyTransitLayers, associateBikeSharing, createAndLink, addStop and buildParkAndRide. For all except the last Walk mode is probably the best but what to use for linking P+R stops since you need walkable and drivable part? use any closest edge as now?

**Comment by mattwigway** [comment]
Can we make two links, one walking avid one driving?

**Comment by buma** [comment]
Probably. I'll take a look.

**Comment by abyrd** [comment]
I'm thinking, in practice doesn't every trip begin and end on foot even if the main mode used is a car? Might it be simpler to always link or preferentially link to walkable edges, and then do a multi phase walk/drive/walk search, as you do with park and ride?

**Comment by buma** [comment]
Two links are made now in P+R. One for closest WALK edge and one for closest CAR edge. If both would connect  to same edge only one is made. Link edges have permissions ALL so they are
 routable by all the modes.
