### ISSUE TITLE
Unexpected decreases in accessibility

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#422]
Using R5 v3.4.1, comparing a scenario with only add-trip modifications to a baseline:
![image](https://user-images.githubusercontent.com/2173529/39262187-af8ebfa2-488c-11e8-9d7a-3b4aeca166cc.png)

![image](https://user-images.githubusercontent.com/2173529/39262206-be837912-488c-11e8-85eb-864a33b54516.png)

Do the red areas (reachable in 20 minutes in the baseline, but not in the scenario with added service) suggest a bug related to linking the newly added stops?   

Another observation, using v3.2.0-70-g84bcb76 and a different scenario with only add-trip modifications:

There are 3 grid cells that show a decrease of 31 jobs reachable:

![image](https://user-images.githubusercontent.com/2173529/39265967-ad54fc2e-4896-11e8-9bd7-1cf765bcf13e.png)

![image](https://user-images.githubusercontent.com/2173529/39266434-ff5d53ee-4897-11e8-8084-4f17b27a7b08.png)

**Comment by abyrd** [comment]
My first thought @ansoncfit, does the baseline include any frequency routes, and what is the number of Monte Carlo draws? Not sure if this cause has already been excluded, but when frequency routes are handled via Monte Carlo selection of randomized schedules, there is no mechanism to ensure that the same randomized schedules are used for the two different scenarios being compared. This means that the baseline could get a slightly advantageous selection of schedules relative to the comparison scenario. The travel times, and therefore the accessibility indicator value, contain a certain amount of noise which is inversely related to the Monte Carlo sample size. Small magnitude changes must be filtered out (hence the whole bootstrap process and probability of improvement computations).

However, if the baseline doesn't contain any frequency routes then adding a line should only cause improvements. In that case the linking process is indeed a likely suspect.

**Comment by abyrd** [comment]
The isochrones are also depending on interpolation between grid cells. The position of the isochrone at a scale smaller than one cell is not necessarily meaningful. However, if I'm not mistaken this is linear  interpolation with none of the overshoot problems that can occur in higher-degree interpolation. Adding a line to a non-frequency network should cause all travel times to be <= their baseline values, and intuitively it seems to me that linearly interpolated isochones for the baseline grid should necessarily fall entirely within those for a grid of >= values (not convinced of this at proof-level though).

**Comment by ansoncfit** [comment]
The baseline network has no frequency routes, so Monte Carlo noise should not be a factor here.

**Comment by abyrd** [comment]
See also #337 which still appears to be happening, at least for car searches.

**Comment by ansoncfit** [comment]
The javadoc for StreetLayer#getOrCreateVertexNear states that it is potentially destructive and that #indexStreets needs to be called first.

#getOrCreateVertexNear is called by #createAndLinkVertex, which is called by StreetLayer#associateStops and StopSpec#materializeOne.   It appears the required street indexing happens in the case of associateStops, but I'm still looking into what happens with materializeOne.

**Comment by ansoncfit** [comment]
It appears the origin may be linking with different streetmodes, even with the stop moved:

 
![image](https://user-images.githubusercontent.com/2173529/39707850-8b2fe234-51e3-11e8-854a-8bc0ba1c300a.png)

In the baseline, the isochrones radiate out from a dead-end for cars, while the blue "scenario" isochrones radiate out from a pedestrian path.

**Comment by ansoncfit** [comment]
The theory we just discussed was that the origin point was being linked to the newly created edge linking the station to the existing road network.  But upon further review, these new "LINK" edges are already discarded as candidates for splitting and starting the street search:

https://github.com/conveyal/r5/blob/701916ee71d9f51f7115118569c648370e52bff2/src/main/java/com/conveyal/r5/streets/Split.java#L104

Back to square one...

**Comment by ansoncfit** [comment]
Splitting the street to link a stop seems to add a cost to traverse the new vertex:

![image](https://user-images.githubusercontent.com/2173529/39842131-58aaca32-53b3-11e8-93d0-45db4b7b70ee.png)

![image](https://user-images.githubusercontent.com/2173529/39842153-6651b524-53b3-11e8-8095-24d14206ecc1.png)


The red isochrone (baseline, no scenario) doesn't change regardless of which side of the station access you start on.

**Comment by mattwigway** [comment]
I think the bug is on line 641 of EdgeStore.java, where the traversal time of the edge is ceilinged - which means that any fractional seconds the edge took to traverse would be treated as one second when there is only one edge, and two seconds when there are two edges (i.e. after splitting). You might need to express time in a finer unit (e.g. milliseconds) or keep time as a float.

**Comment by ansoncfit** [comment]
It appears origin linking, not just edge traversal, is involved.  In the previous screenshot, if the origin is moved slightly west, past the intersection with Barham Ave., the isochrones are coincident.

**Comment by ansoncfit** [comment]
In other words, if you link to an edge that was not split, the problem does not occur even if you then traverse the split edge.  The problem appears only when you link to the split edge.

**Comment by ansoncfit** [comment]
It appears the issue is that vertices of the initial (split) edge are reached in no time.  In the baseline, this is teleporting a full block, while in the scenario with the new stop, it's only teleporting to the split point for the new station.  See recent comment in #360.
