### ISSUE TITLE
Park and ride support

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#44]
This is conceptually similar to #43 and I think can be implemented in the same way. We first do a driving search, then a multiorigin walking search from the reached park and rides.

**Comment by mattwigway** [comment]
We also need to determine where the park and rides are. @mattwigway will discuss with @abyrd.

**Comment by mattwigway** [comment]
I'll be working on this this afternoon perhaps into tomorrow.

**Comment by mattwigway** [comment]
Park and rides are linked in 7e6d602a1e505391357d50ac02e32af5912db9b9 and get vertex flag PARK_AND_RIDE.

**Comment by buma** [comment]
Routing with CAR_PARK in access works. Only code needs to be refactored to also support B+R and Bike sharing in access leg.
