### ISSUE TITLE
Improve upload of opportunity dataset as CSV

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#441]
An "N/A" or similar value lurking at the bottom of a CSV can cause issues, and without a warning, a user may not know to look for it.

**Comment by ansoncfit** [comment]
Related issue: common use case is to upload lat/lon with no other columns, expecting analysis to understand each row as one opportunity.

**Comment by abyrd** [comment]
It took me a moment to understand the comment above so just clarifying: each row is expected to have a "quantity" or "magnitude" field. When this field is absent, quantity can be assumed to be 1.
