### ISSUE TITLE
Exact itineraries

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#46]
We need to be able to produce exact itineraries for options. I think this would be best done by just interleaving the schedules after the fact, because it may be that a particular option is available every ten minutes but is only optimal every 30.

This requires bundling of patterns, for instance we want a commute from Van Ness-UDC to Shaw-Howard in DC to show the schedule for the red line transferring to either the green or yellow line.

**Comment by abyrd** [comment]
We should define some terms for later readability: "Options" is used in the sense of our profile routing API: a specific sequence of bundles of trips, where each bundle contains only trip patterns connecting the same two clusters of stops. And I think what you mean by "exact itineraries" is complete timetables of every time a particular option can be carried out, whether or not those instances are optimal.

**Comment by mattwigway** [comment]
We will use the patterns in the path and then scan back over the transit layer to find the times that path is possible.

**Comment by mattwigway** [comment]
We'll also compute averages at this stage because we want an average for each option independently.

**Comment by mattwigway** [comment]
It turns out I need to do both these things in order to make #45 work correctly, so I'll take care of this.

**Comment by abyrd** [comment]
We no longer use profile routing in the sense it is mentioned here. Closing.
