### ISSUE TITLE
Scenario-added routes are always trams

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#465]
When enabling or disabling transit modes in an analysis, all routes added by scenarios are treated as trams.

There is no UI element to set the mode of a newly added route, but when an AddTrips object is initialized, its `mode = Route.BUS`. Applying this modification to the network does not copy the mode info into the new instance of com.conveyal.r5.transit.RouteInfo, which is where the router looks for it. So the field com.conveyal.r5.transit.RouteInfo#route_type remains uninitialized at 0, which in GTFS means "tram".

**Comment by ansoncfit** [comment]
Related: https://github.com/conveyal/analysis-ui/issues/806
