### ISSUE TITLE
Retain network build warnings

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#487]
We just discovered some negative travel time warnings in a network while watching the worker logs. If we didn't look at the logs, these would slip through and affect analysis silently. When a worker is building a network, it would be helpful to save all warnings and errors from that worker's logs to a file that can be opened from the Analysis UI. The existence of such a file with warnings and errors should be very visible so the user knows something might be wrong with the network.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/r5/pull/713 closes.
