### ISSUE TITLE
TravelTimeReducer does not check maxTripDurationMinutes limit for single-point requests

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#522]
The TravelTimeReducer checks whether total travel times (including pointset linkage costs)  exceed `maxTripDurationMinutes` (as set from the request coming from the UI by `populateTask() ` in `analysis-backend AnalysisRequest`) and correctly calculates accessibility results.

For single point requests, however, total travel time can be set in the UI after results are received, and this check is skipped.  It shouldn't be strictly necessary, as `populateTask()` doesn't reset the default (maximum) value of `maxTripDurationMinutes`. But without the check, overflow issues can lead to anomalies in the UI for some destinations more than 255 minutes away from origins.

See discussion at https://github.com/conveyal/analysis-ui/issues/665

**Comment by abyrd** [comment]
It's good to have this identified and fixed, since if I'm not mistaken this doesn't only lead to isochrone display anomalies, it will also count opportunities in the overflowed cells in accessibility numbers (but only in single-point interactive results).
