### ISSUE TITLE
Divide by 0 error in NetworkPreloaderProgressListener

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#547]
`this.updateFrequency = totalElements / 100` floors, so for networks with fewer than 100 stops, `currentElement % updateFrequency` throws a / by 0 error.

**Comment by abyrd** [comment]
Looks like this is solved by ac4d5574a0ad61c261ec0b5e1917cf17dc52359a. I added a comment to make sure no one reverts the change.
