### ISSUE TITLE
Check bounding box size for uploaded points

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#548]
`Grid` uses `MAX_BOUNDING_BOX_AREA_SQ_KM` to check the size of opportunity datasets uploaded as polygon shapefiles.  We should add a similar check for uploaded point features, or filtering out points that are beyond a region's bounds. Otherwise the backend could stall trying to create a large grid encompassing all the points.

**Comment by abyrd** [comment]
I can imagine people would want to upload large sets of points and keep only those falling within the analysis region. This is some processing we should be able to do pretty simply on the server or worker side. But there's something to be said for not transforming the inputs automatically, and requiring any modifications to be done intentionally.

**Comment by ansoncfit** [comment]
Follow-up: after about 30 minutes, backend finished processing the point file in question and uploaded the grid to S3.  It was about 3MB gzipped, and attempting to load it in the front-end as an opportunity dataset crashed the browser.

So we should implement some way of preventing excessively large grids (e.g. covering all of New Zealand) from being created -- let's decide whether to reject large uploads with an error or clip on the server.

**Comment by ansoncfit** [comment]
We should address this in #529
