### ISSUE TITLE
maven install fail

### ISSUE THREAD

**Issue by achievermina** [conveyal/r5#553]
While installing r5 using maven, it is showing errors.
Thank you in advance. 

`
Tests run: 1529, Failures: 0, Errors: 44, Skipped: 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.841 s
[INFO] Finished at: 2019-09-17T20:53:07-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project r5: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/mina/r5/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

more detailed error messages are below
`
Tests in error:
  testSetDwellTimeRoute(com.conveyal.r5.analyst.scenario.AdjustDwellTest)
  testSetZeroDwellTimeRoute(com.conveyal.r5.analyst.scenario.AdjustDwellTest): Could not initialize class com.conveyal.r5.streets.Split
  testScaleTripSegmentDwellTime(com.conveyal.r5.analyst.scenario.AdjustDwellTest): Could not initialize class com.conveyal.r5.streets.Split
  testScheduleRetention(com.conveyal.r5.analyst.scenario.AdjustFrequencyTest): Could not initialize class com.conveyal.r5.streets.Split
  testPhasing(com.conveyal.r5.analyst.scenario.AdjustFrequencyTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddedScheduledTrips(com.conveyal.r5.analyst.scenario.AdjustFrequencyTest): Could not initialize class com.conveyal.r5.streets.Split
  testConvertingMultiplePatternsToFrequency(com.conveyal.r5.analyst.scenario.AdjustFrequencyTest): Could not initialize class com.conveyal.r5.streets.Split
  testFrequencyConversion(com.conveyal.r5.analyst.scenario.AdjustFrequencyTest): Could not initialize class com.conveyal.r5.streets.Split
  testChecksumStability(com.conveyal.r5.analyst.scenario.ChecksumTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddBidirectionalTrip(com.conveyal.r5.analyst.scenario.RelinkingTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveByRoute(com.conveyal.r5.analyst.scenario.RemoveTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveSpecificTrips(com.conveyal.r5.analyst.scenario.RemoveTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  adjustSpeedSegment(com.conveyal.r5.analyst.scenario.AdjustSpeedTest): Could not initialize class com.conveyal.r5.streets.Split
  adjustSpeedOneTrip(com.conveyal.r5.analyst.scenario.AdjustSpeedTest): Could not initialize class com.conveyal.r5.streets.Split
  adjustSpeedWholeRoute(com.conveyal.r5.analyst.scenario.AdjustSpeedTest): Could not initialize class com.conveyal.r5.streets.Split
  adjustSpeedWholeRouteButDontAdjustDwells(com.conveyal.r5.analyst.scenario.AdjustSpeedTest): Could not initialize class com.conveyal.r5.streets.Split
  testRerouteInMiddle(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  testDivertEnd(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  testDivertStart(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  testExtendRouteAtBeginning(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  insertStopInMiddle(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  testExtendRouteAtEnd(com.conveyal.r5.analyst.scenario.RerouteTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddUnidirectionalTrip(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddUnidirectionalTripWithPhasing(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddUnidirectionalTripWithAddedStops(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddExactTimes(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testMultipleFrequencyEntries(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testAddBidirectionalTrip(com.conveyal.r5.analyst.scenario.AddTripsTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveTooMuchTime(com.conveyal.r5.analyst.scenario.RemoveStopsTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveStops(com.conveyal.r5.analyst.scenario.RemoveStopsTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveTime(com.conveyal.r5.analyst.scenario.RemoveStopsTest): Could not initialize class com.conveyal.r5.streets.Split
  testRemoveFirstStop(com.conveyal.r5.analyst.scenario.RemoveStopsTest): Could not initialize class com.conveyal.r5.streets.Split
  testGetMercatorEnvelopeMeters(com.conveyal.r5.analyst.GridTest): java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
  testRoundTrip(com.conveyal.r5.kryo.KryoNetworkSerializerTest): Could not initialize class com.conveyal.r5.streets.Split
  testNoTurnBothSplit(com.conveyal.r5.streets.TurnRestrictionTest): Could not initialize class com.conveyal.r5.streets.Split
  testNoTurnWithSplitReverse2(com.conveyal.r5.streets.TurnRestrictionTest): Could not initialize class com.conveyal.r5.streets.Split
  testNoTurnWithSplitDestination(com.conveyal.r5.streets.TurnRestrictionTest): Could not initialize class com.conveyal.r5.streets.Split
  testNoTurnWithSplitOriginReverse(com.conveyal.r5.streets.TurnRestrictionTest): Could not initialize class com.conveyal.r5.streets.Split
  testNoTurnSplitOriginTurnRestriction(com.conveyal.r5.streets.TurnRestrictionTest): Could not initialize class com.conveyal.r5.streets.Split
  testReverseRouting(com.conveyal.r5.streets.ReverseRoutingTest): Could not initialize class com.conveyal.r5.streets.Split
  testSimpleTurnRestriction(com.conveyal.r5.streets.StreetLayerTest): Could not initialize class com.conveyal.r5.streets.Split
  testComplexTurnRestriction(com.conveyal.r5.streets.StreetLayerTest): Could not initialize class com.conveyal.r5.streets.Split
  testSplitsForStops(com.conveyal.r5.streets.StreetLayerTest): Could not initialize class com.conveyal.r5.streets.Split
  testSplits(com.conveyal.r5.streets.StreetLayerTest): Could not initialize class com.conveyal.r5.streets.Split
`

**Comment by ansoncfit** [comment]
Closing, as we now use gradle instead of maven.
