### ISSUE TITLE
Fractional opportunity quantization error

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#566]
Our opportunity grids are saved using integers. The intent is to make them relatively compact, fast and easy to operate on within Javascript typed arrays.

However, internally in the backend and workers we allow fractional opportunities. These can especially arise when rasterizing polygons into an opportunity grid. We want to preserve the total number of opportunities within the polygon, and we want overlapping polygons to sum properly. Fractional opportunities are also convenient for certain types of advanced capacity-constrained analysis where opportunities are distributed fractionally to all individuals that can reach them.

Problems arise when converting these fractional counts to integers. You can either truncate or round them, and we do the latter. If you've got two overlapping polygons, the first one having 0.49 opportunities per cell and the second 0.51 per cell, the first one will just disappear while the second one remains. All the cells within a polygon will often round one way or the other in lockstep. The exception with overlapping polygons is even more weird: if the first one has 0.49 opportunities per cell and the second 1.01 per cell, the first will disappear, the second will round to 1, and the overlap will round to 2. 

This problem is most visible where cells have zero or one opportunity, but the effect exists for larger counts as well. It may seem minor since each cell is only off by one, but since they're all off in the same direction it can bias the total number of opportunities by up to half the the total number of cells.

This kind of quantization problem is thoroughly understood and solved in digital audio or image processing. The usual solution is to apply dithering. A simple approach of adding random dithering noise could work for us, with the downside that the allocation of polygon opportunities to grid cells then becomes non-deterministic, so accessibility results are not stable. It would also be strange to accept that the total number of opportunities would only probabilistically match the inputs. We would probably need a more sophisticated dithering approach that ensured the sum of opportunities from each polygon or in each neighborhood of a certain size post-dithering remained the same. This could get quite complicated. 

This is more or less the idea of error-diffusion dithering. As you iterate over the cells (either for a polygon or the whole grid) the remainder from each rounding operation is carried over to the next cell (or to several adjacent cells across and down). However this has a spatial/directional bias, and doesn't exactly preserve the total number of opportunities because error can "fall off" the right or bottom edge of the grid. The bias comes from the fact that these approaches operate in one pass, and avoid diffusing error backward to pixels that were already examined. There's probably an iterative convergence approach that diffuses in all directions. There must be research on this but it's buried in image processing literature that is not concerned with preserving the sum of the pixels.

It would also be possible to migrate our grids to use floats or fixed-point fractional integers, but this is a big change. It might have space and speed impacts, and only helps when fractional opportunities are present. Annoyingly, floats have exactly the same endianness problem as ints (Java writes big-endian, while almost all modern processors are little-endian).

**Comment by abyrd** [comment]
This paper confirms that error is typically diffused in a particular direction which introduces directional hysteresis: http://www.eie.polyu.edu.hk/~enyhchan/FMEDforDH.pdf
It has a bibliography mentioning a few methods that achieve symmetric error distribution.

It's important in our case though that when rasterizing each polygon the opportunity density for each (fully intersected) grid cell is the same. If we did the quantization at that point, it matters a lot less where the error is diffused to, as long as it's deterministic and kept proportionate to cell coverage by the polygon. Nonetheless, in non-iterative approaches there's always the possibility of error being left over at the end of the pass.

**Comment by abyrd** [comment]
Basic error diffusion in the grid writer:
```Java
// Delta coding and error diffusion are reset on each row to avoid wrapping.
int prev = 0;
for (int y = 0; y < height; y++) {
    // reset on each row to avoid wrapping error.
    // alternative is to use serpentine iteration.
    double error = 0;
    for (int x = 0; x < width; x++) {
        double val = grid[x][y] + error;
        int rounded = ((int) Math.round(val));
        error = val - rounded;
        int delta = rounded - prev;
        out.writeInt(delta);
        prev = rounded;
    }
}
out.close();
```

It works on my shapefile that yields 0.47 opportunities per cell: 
<img width="250" alt="Screen Shot 2019-11-28 at 16 38 10" src="https://user-images.githubusercontent.com/112871/69790454-796ff580-11fd-11ea-85e0-7125cc4c14c0.png">

**Comment by abyrd** [comment]
Looking at this again. If we start with the basic error diffusion code in a comment above, it needs to be adapted to constrain output values to be non-negative. In the current form I believe it can generate negative integral pixel values even if all inputs are positive, for example if error from rasterizing the last pixel on the edge of a shape is -0.4 and the next pixel written has a target value between 0.0 and 0.4. This should also be accompanied by tests equivalent to the image shown, where a shape with fractional density per pixel is rasterized, written out, reloaded, and summed, asserting the sum to be within 1 of the original magnitude of the polygon.

**Comment by abyrd** [comment]
I think my concern above about negative densities was unfounded. It doesn't matter whether the floating point target value is negative, it matters that the rounded integer value (which is stored in the file and read when the file is loaded) is non-negative. The most negative error that can result from rounding is -0.5, and the smallest number that can result from adding this to a non-negative density is -0.5. That should always round up to 0, cascading a positive error to the next cell. I'll just add some assertions that input densities and rounded values are non-negative.

**Comment by abyrd** [comment]
Diffusion added in d5a1f0b7114170ccb128c14794b77eca5d36dc38 has directional bias (eastward) and up to one half opportunity can be lost per row of pixels. This is probably not worth improving with iterative diffusion, to improve we should eventually migrate to a file format supporting fractional counts and eliminate the need for diffusion.

**Comment by ansoncfit** [comment]
Fixed in https://github.com/conveyal/r5/pull/689
