### ISSUE TITLE
Comparison of R5 and OTP

### ISSUE THREAD

**Issue by nickaein** [conveyal/r5#575]
This project and [OTP](https://github.com/opentripplanner/OpenTripPlanner) seems to be most promising open-source routing engines available for public transport route planning.

I am still not sure about their pros and cons with respect to each other as a route planner for public transit. Based on the information available on repositories and conveyal website, it seems that:

1. Unlike OTP, R5 is mainly focused on trip analysis and point-to-point routing is a second-class feature.

2. As mentioned in [this article](https://www.conveyal.com/trip-planning), a major feature of R5 is *profile* routing. Specifically, supporting time-windows and considering reliability of different travel paths for the user.

3. R5 has been under active-development since 2015 while the contributions to OTP has been dropped. Is there the possibility that it ends up in maintenance or even becomes deprecated in near future?

Are these impressions accurate?

What are the other major differences between R5 and OTP that one should consider before choosing one of these engines?

P.S.: It would be very helpful to newcomers like me to have a "comparison section" on README/Wiki of either of these projects.

**Comment by slabiak** [comment]
Hi, I actually wanted to ask the same question so I would be grateful if someone could reply to it. The most important thing for me is which one has better performance and which one consumes less cpu/memory? (I just want to have simple endpoint where I will give lat/lng of starting point and destination and would like to have response which will tell me what will be total trip time for walk+transit mode).

Regarding your 3rd question - OTP development is not dropped, they are actively working on OTP 2.0  which was expected to be released as beta in Q1 2020, you can check latest commints on dev-2.x here: https://github.com/opentripplanner/OpenTripPlanner/tree/dev-2.x

**Comment by ansoncfit** [comment]
Hi @nickaein, this discussion in the OTP Users group may be helpful: https://groups.google.com/g/opentripplanner-users/c/fFtI2gSjTEg/m/awmhXQsACAAJ

I would say impressions 1 and 2 are accurate. R5 is focused on analysis applications, as opposed to passenger-facing journey planning. As @slabiak noted in reference to impression 3, OTP development has not been dropped.

We can try to make these points clearer in the R5 readme.

**Comment by nickaein** [comment]
@ansoncfit Thanks for pointing it out! That was an interesting read and very informative.
