### ISSUE TITLE
Frequency routes seem to cause early bail-out from RAPTOR

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#58]
Using scenario Modifications, I create new TripPatterns containing a single frequency-based TripSchedule. 

As a test I made a Modification that creates a TripPattern with only three stops, and a frequency-based trip that moves extremely quickly across Portland stopping only at those three stops (60 seconds per hop, 30 seconds dwell time). The goal was sanity-checking, to see if this produces the expected pattern and magnitude of accessibility improvements on the map.

From certain single-point analysis locations, the results are exactly as expected. From other locations nearby, there is no change at all in reachable area. Logs indicate that when there is no change in reachable area, the RAPTOR search is terminating after only two rounds. When correct results are displayed, the RAPTOR search runs for 8 rounds.

This could of course be due to a mistake in my implementation of new TripPattern creation. But it seems to be most sensitive to the departure location, which makes me suspect an interaction with some other underlying problem.

**Comment by mattwigway** [comment]
Oh. I wonder if transfers are being created to the new trip pattern? Otherwise the origin would need to be within walking distance of one of the new stops.

**Comment by abyrd** [comment]
The trip patterns I'm adding re-use existing stops, creating no new stops. So that shouldn't be the problem

**Comment by mattwigway** [comment]
Ah. I wonder if the new patterns are getting marked correctly? There are
two places where patterns get marked to be explored, one in doTransfers and
one somewhere near the initial stop search.

On Mon, Jan 4, 2016 at 5:38 AM, Andrew Byrd <notifications@github.com>
wrote:

> The trip patterns I'm adding re-use existing stops, creating no new stops.
> So that shouldn't be the problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/58#issuecomment-168677915>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
Actually there's one more place, in runRaptorFrequency, where all frequency patterns are (supposed to be) marked.
