### ISSUE TITLE
Isochrone generation

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#6]
We can use the output from #4.

**Comment by abyrd** [comment]
On a Portland Oregon data set, current R5 isochrone generation code seems to calculate forever, generating large numbers of "ring ended unexpectedly" errors. On the Dutch data set generating isochrones was observed to lock up the worker machine entirely.

Of course we have other (raster) methods of generating isochrones and this vector implementation is just a first iteration, but we should probably either add a better bail-out mechanism or disable it until we're sure it doesn't lock up workers.
