### ISSUE TITLE
Street network changes

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#60]
We need to be able to modify the street network as well as the transit network when creating a scenario. The simplest way to do this from the UI side would seem to be to adapt the [iD editor](https://github.com/openstreetmap/id), which generates OSM changesets. We can already read OSM changesets in OSM-lib, but that doesn't allow us to apply a modification on the fly.

One cloogy thing to do would be to say that the street network modifications are part of the bundle and that modifying the street network requires creating a new bundle. I'd rather not do that; it would be preferable to have instant feedback whenever the street network is changed, which requires implementing the street network changes directly on the R5 graph, probably by saving some information from OSM (e.g. way IDs for edges, vertex ID for nodes). We'd likely just drop all of the edges that came from ways that had been changed (and not do anything about nodes; if a node is deleted though we would need some way to know which ways need to be reconstructed, which also requires having the original OSM data available to reconstruct the remainder of the way, which is messy).

The problem with all of this is that changes to the street network require re-doing stop linking and rebuilding stop trees, at least in the local area, which has the potential to be slow.

**Comment by abyrd** [comment]
Current practice as of April 2020 is to make street modifications by uploading modified OSM. Our next stage is to create one new modification type to add simple linestring roads which are auto-stitched into any road they cross, and another new modification type to delete all edges intersecting a polygon.

**Comment by abyrd** [comment]
The UI side of this is conveyal/analysis-ui#1085.
