### ISSUE TITLE
Mark bundle state ERROR when OSM loading fails

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#608]
Uploading bad OSM fails silently until you try to use the OSM in an analysis. If I upload a bad OSM file with a good GTFS file, the UI eventually shows the newly created bundle as if there were no problems, without the ERROR suffix we see on GTFS load failures. You don't realize anything's wrong until you kick off a single point analysis, you then get "Error communicating with the server" with a NullPointerException at TransportNetworkCache.java:111.

This is because in OSM.readPbf(), OsmLib doesn't throw exceptions, it logs them and exits cleanly.

This OSM processing is being wrapped in an asynchronous task which has its own exception handling and can report errors. The exception is hidden and cascades another error that is successfully caught by the background task's ErrorTrap. But the original exception it should be caught farther down, in the heavyTask's catch clause.

Related to conveyal/analysis-backend#15. For both OSM and GTFS we should try to expose more detailed errors to the UI.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/r5/pull/713 closes.
