### ISSUE TITLE
Determine long-term strategy for working polling

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/r5#613]
From https://github.com/conveyal/analysis-backend/pull/130#discussion_r183316865

> We could expose all endpoints publicly and just somehow give the workers credentials to contact this one - not auth0 credentials, but some key only the workers would know but not someone trying to mess with the system. The alternative is to block particular endpoints in the reverse proxy but that is an extra custom setup step that might be nice to avoid if we find a simple way.

**Comment by ansoncfit** [comment]
Address with #596
