### ISSUE TITLE
getTimetables (used in scenario editor) slow

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#631]
In a recent attempt to copy timetables in Altanta, the TimetableController took 2.6 minutes to respond. We should streamline the search through regions/projects/modifications and look into relevant database indexing.

**Comment by abyrd** [comment]
Note from meeting discussion: this is about copying timetables from scenario modifications, not fetching timetables from GTFS (which would be a completely different code path). Probably just requires indexing in Mongo.
