### ISSUE TITLE
Nondestructive street splitting

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#64]
The current street splitting method resizes the edge to be split, reusing that existing edge as the first half of the street leading up to the split point, and creating only one new edge pair which will serve as the second half of the street leading out of the split point.

This is great for initial graph building but will not work for temporary scenario modifications unless we perform a deep copy of the entire street network before applying modifications. It seems kind of absurd to create a complete copy of an entire country just to add one transit stop, so I plan to nondestructively extend the baseline graph (see #62).

So we must modify com.conveyal.r5.streets.StreetLayer#getOrCreateVertexNear to make reusing/resizing the existing edges optional. If reuseExistingEdge=false, two new edge pairs will be created, one leading up to the split and one leading out. This leaves the original edge in place, which should be harmless but we could also flag it as deleted in the modified graph (see #63).

**Comment by mattwigway** [comment]
One would think that leaving the existing edge pair in place would be harmless but this actually has caused us issues in the past. Consider the case where new transit routes split the same edge pair twice, and this is a location where one might want to transfer from one new route to the other. Depending on the order that the stops and edges are encountered and linked, you'll get one of the following:

![image](https://cloud.githubusercontent.com/assets/566958/12159740/c0f30c32-b499-11e5-8102-e32cd50cf666.png)

in a potentially non-deterministic way. Clearly if a street gets split a second time we want to make sure that the new edges get split. Of course this also means making sure that each temporary edge gets added to the spatial index when it is inserted.

**Comment by abyrd** [comment]
True, we need to keep this problem in mind. But it's not scalable to duplicate the entire edge store and spatial index, so we need an alternative to both. On the spatial index side, it may work to just not index any nondestructively added edges (they'd be kept in a list and included in the response to every spatial index query, since such queries are expected to overselect). To allow single-thread-visible deletion of edges, there's #63.
