### ISSUE TITLE
EdgeStore.remove is inefficient

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#65]
The TIntList.remove(index, count) method would have to copy the whole tail of the array to remove an element. It's being called many times (sometimes thousands of times) in a row with the tail of the array being re-copied each time. This is probably slow.

A better approach would be to do a single-pass copy of all the arrays in parallel, skipping the indexes that are in the set edgesToRemove.

**Comment by mattwigway** [comment]
We now don't remove edges, we just remove their traversal permissions.
