### ISSUE TITLE
Average accessibility directly rather than deriving average accessibility from average travel time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#66]
We currently compute the average travel time to a destination and use that to compute an average accessibility. We should probably compute the average accessibility directly, by computing the accessibility for every departure minute and then averaging that. It's important to note that this is a different measure: before we were counting what _specific_ opportunities could be reached in an average travel time of X, now we're counting only how many opportunities can be reached; the specific opportunities can differ at every minute.

Extensive discussion copied from conveyal/browsochrones#19 follows:

Even though we're reporting the average number of jobs accessible, that doesn't really capture the true picture of things. No individual cares about how many total jobs they can reach, they care about whether they can reach their job(s) (which are small in number relative to the total number of jobs in the city). Consider these three scenarios:

I have a reliable mass transit system, running every 2 minutes, that lets me reach 100,000 jobs on average.
There are two trains I can take. One goes into City A (where there are 100,000 jobs) and the other goes to city B (where there are also 100,000 jobs). However, the first train runs only between 7-8 AM and the second train runs only 8-9 AM. Assume the trains reach all the jobs in exactly 60 minutes.
Same as scenario 2, but now there local buses that run when the trains aren't running, and take 75 minutes.
If we compute average accessibility by computing accessibility at every minute, both scenarios show that 100,000 jobs are reachable. If we compute it using the average travel time, but downweighting by percent of time the destination is accessible at all, the first is still 100,000, the second is still 100,000 (0.5 \* 100,000 + 0.5 \* 100,000), and the third is 0 (because the average travel time is now 67.5 minutes).

Well that kind of calls into question the whole idea of using average travel time to derive accessibility (which is also what we've been doing in Analyst up to this point, see opentripplanner/OpenTripPlanner#2148). Adding lines should never cause decreases in accessibility. So I guess that's out.

**Comment by mattwigway** [comment]
This is very important issue and I almost want to leave it open for historic reasons, but I'll refrain.

**Comment by abyrd** [comment]
But you did leave it open :)
