### ISSUE TITLE
Index out of bounds in small grids

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/r5#671]
It's possible to get an `Index out of bounds error` on line78 of the following:

https://github.com/conveyal/r5/blob/d8dbcda9677ab0fe5271f6d767a69266331eaff4/src/main/java/com/conveyal/analysis/SelectingGridReducer.java#L70-L82

Create a regional analysis with bounds: 
```
bounds: { // This is taken from Cypress tests. Location is in Covington, Kentucky.
  north: 38.9577,
  east: -84.3969,
  south: 38.9570,
  west: -84.3966
}
```
This will generate region with 2 origins, with a height = 1, and a width = 2.

It's unlikely to occur in practice. But being able to generate this type of error in general may uncover the need for more bounds checking in this code.

**Comment by trevorgerhardt** [comment]
I created a related, failing test in Cypress: https://github.com/conveyal/analysis-ui/pull/1427

**Comment by abyrd** [comment]
This only affected files < 72 bytes in length. Files of normal length were not affected. Full explanation in bugfix PR #686.
