### ISSUE TITLE
Many-to-many with scenario uses massive amount of memory

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#68]
The full text of the scenario is repeated for every origin, both as objects and as strings, both when creating the JSON representation and when receiving it on the broker. Usually this is exactly the same object tree or string repeated tens of thousands of times, which eats many GB of memory.

We need a means to send this only once instead of sending it with every origin.

**Comment by abyrd** [comment]
@mattwigway and I have discussed this and have a plan to make scenarios scalable. 

First, in the short term we will store the scenarios on S3 and refer to them by UUID rather than including the full text of the scenario in every request. The broker will still have a list with one separate object per task, but they'll be much smaller. The workers will fetch the scenarios from S3 and keep them in a local cache.

Second, in the long term we will not even send all the individual tasks to the broker. We will send a single template request together with a list of origin coordinates to substitute in to that template request. The broker will then no longer have a list of tasks per job, it will have bitsets per job tracking which tasks have been delivered and completed.

There will be two ways to specify the list of origin coordinates to substitute in to the template request: a plain list of numbers or a parametric description of a web mercator grid. These same two methods could be used to specify the analysis destinations to keep the tasks rather generic.

It would also be possible to store the job itself (including the scenario) on S3 using a UUID and have the broker only tell the workers which numbered tasks within the job they should do. They would substitute in the origin points themselves to "materialize" the specific tasks to perform.

**Comment by abyrd** [comment]
The problem with storing jobs on S3 is that the system needs to work for both batch jobs and single-point requests. We'd be storing a new job under a new UUID on S3 every single time someone dropped a pin. On the other hand, S3 objects can be set to expire after a while so they'll just evaporate, and S3 might be fast enough to make all this invisible. The simplicity of every single point request being a job of length 1 is appealing.

**Comment by mattwigway** [comment]
As far as I can tell this requires more or less rewriting the broker from
scratch. If we're going to do that anyhow, we may as well just write it in
node. Development is happening at https://github.com/conveyal/broker.js

On Wed, Jan 13, 2016 at 10:26 AM, Andrew Byrd <notifications@github.com>
wrote:

> The problem with storing jobs on S3 is that the system needs to work for
> both batch jobs and single-point requests. We'd be storing a new job under
> a new UUID on S3 every single time someone dropped a pin. On the other
> hand, S3 objects can be set to expire after a while so they'll just
> evaporate, and S3 might be fast enough to make all this invisible. The
> simplicity of every single point request being a job of length 1 is
> appealing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/68#issuecomment-171330247>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC
