### ISSUE TITLE
Port DC fare module

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#69]
We need to port at least the DC fare module.

**Comment by mattwigway** [comment]
https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/profile/DCFareCalculator.java

**Comment by mattwigway** [comment]
Hold off until middle of next week once we can discuss r5 fare support with @abyrd.

**Comment by mattwigway** [comment]
We'll implement this as a function that can take a complete path or a partial path and return a cost for that path.

**Comment by buma** [comment]
I compared Fares from R5 and http://www.carfreeatoz.com/ and they were the same when same transit combination was used.

Fares work now for profile routing but not yet for point to point since it has to be determined which fare is for which part of a trip.

**Comment by buma** [comment]
Found reason for NULL fares. Some routes don't have agency or agency URLs set in GTFS data for that reason They can't be classified and they don't get fare.
