### ISSUE TITLE
Unify CSV rasterization

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#696]
We currently have two different ways of converting CSV files of points into grids. Our original CSV rasterization automatically detects all numeric fields and makes one layer per numeric CSV column. Our newer process of making freeform pointsets from CSV requires one specific count field to be chosen, and converts the resulting freeform pointset into a grid. This freeform-to-grid conversion was originally intended as a stopgap measure to allow visualization of points in the map UI, and previewing accessibility results in a single point analysis (which can't display freeform points) before running a regional analysis with the true freeform layer. 

However, thinking through the UI for these various features we realized it's confusing to have two different code paths with different behavior and different parameters for rasterizing CSV. We should ensure CSV points are always converted to raster by a single code path, and try to align its parameters with the CSV-to-Freeform parameters.

In the short term, to facilitate unification we could sacrifice the ability to automatically generate multiple layers at once from a single CSV file. In fact we find automatic selection of multiple columns generates junk layers as often as not. We would not be bothered by uploading a CSV multiple times to create layers from multiple columns.

Note also that automatic column selection and multiple column selection are two independent features. I think the ideal is manual multiple column selection, and a bonus would be selection from known column names based on a pre-scan of the CSV header row (and potentially full type validation of the columns) on the UI side.

This could also tie in to a UI change where when uploading CSV, there are two independent switches for creating a raster and creating a freeform layer, both always using the same parameter fields (count and id columns, lat and lon columns etc.)

We also need to consider our existing special functionality for uploading matched OD pairs as CSV for one-to-one freeform-to-freeform analyses.

**Comment by ansoncfit** [comment]
Closing for now. We'll flesh out the `CsvDataSourceIngester` added in #732 when we get to #761
