### ISSUE TITLE
Additional GTFS modes

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#697]
As of https://github.com/google/transit/pull/174, 11 (Trolleybus) and 12 (Monorail) are valid `route_type` values.

We should revise R5 with some consolidation, keeping in mind that adding even more specific mode selectors in the UI (a la https://github.com/conveyal/analysis-ui/issues/718) is not desirable.

**Comment by ansoncfit** [comment]
See also https://github.com/conveyal/r5/issues/476

**Comment by abyrd** [comment]
Discussed in a meeting: there is already a confusing number of mode selectors in the UI. We will group all the uncommon modes as "other", then if anyone wants to select them individually they can use the JSON.

**Comment by trevorgerhardt** [comment]
Addressed in #774 & https://github.com/conveyal/ui/pull/1689
