### ISSUE TITLE
Transfers to add-trip modifications at re-used stops

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#699]
We noticed that transfers from loop routes (e.g. the CTA Orange Line) to add-trip modifications only work in certain directions, apparently determined by which baseline platform the new scenario route stops closest to.
![image](https://user-images.githubusercontent.com/2173529/109240395-699ae480-77a5-11eb-8ded-f296bc0a2bd2.png)

Let's check:
* Pattern reboard restrictions
* Transfers to closest stop
* Index of patterns through stops that is not updated by scenarios
* Changes introduced by https://github.com/conveyal/r5/pull/640

**Comment by abyrd** [comment]
It just occurred to me that on this kind of route, the two platforms of the station for opposite directions are on the same pattern. We only create transfers between stops on different patterns.

**Comment by ansoncfit** [comment]
Here's an example of the transfer not working near the end of an existing route, when there are separate patterns for the two different directions (i.e. not a loop route).

The blue added trip stops at an existing stop, the second stop on the southbound pattern of MBTA Route 350
![image](https://user-images.githubusercontent.com/2173529/140843066-8578fe30-0947-4748-9bcf-bd6c8008a409.png)

On the 350 northbound, the closest stop is the last stop (which happens to be the first stop of the southbound pattern):
![image](https://user-images.githubusercontent.com/2173529/140842977-4d8f4cd8-10f6-49a3-9663-156d37006526.png)

With a maximum of 1 transfer allowed, we would expect riders from the south to ride to the last stop of northbound Route 350, then walk back south to the transfer stop.

But instead, from origins in the south there's no access east along the added trip, suggesting the transfer is somehow disallowed. Access does show up on the added trip if:
1. The transfer limit is increased to 2. The returned path shows a ride on the 350 northbound, a transfer to the 350 southbound at the end of the line (after a ~15 minute layover, to ride 1 stop), and a transfer to the added trip.
2. The stop on the added trip is nudged slightly, so that it does not re-use the existing 350 southbound stop. The returned path shows the expected itinerary (with only 1 transfer).

**Comment by ansoncfit** [comment]
The initial case reported in this issue makes sense given the design of `TransferFinder#retainClosestStopsOnPatterns`: see related comments about this optimization yielding incorrect results "for some loop and U-shaped routes." 

Something else seems to be the cause of the second case I reported. That behavior appears to be consistent going back to at least R5 v4.5.1.

**Comment by ansoncfit** [comment]
Ah -- even though the two stops in question are on different patterns, `retainClosestStopsOnPatterns` probably filters out the transfer between them because some other pair of northbound/southbound stops has a shorter distance between them. And there's no transfer search re-run for baseline stops after scenario application, even if these stops are used by a new pattern (see `nStopsToProcess`). So the transfer to the added trip isn't found.

Next step is probably testing performance with the `retainClosestStopsOnPatterns` optimization disabled, as already suggested in the Javadoc on that method. The performance penalty may be mitigated somewhat by the revised pattern filtering/caching introduced over the last year.

**Comment by abyrd** [comment]
We discussed this at today's meeting and decided to explore increasing the number of transfers and observing whether there's any appreciable impact on resource consumption. Currently we only retain one transfer between each pair of patterns, which is quite strict and seems to be responsible for many of the problems reported on this issue. I was a little concerned about computing transfers between every pair of stops, as this has the potential to grow supralinearly in certain data sets (even if the all-pairs search is distance limited). A good intermediate option might be to find the closest stop on each other pattern for each stop in each pattern. On a common trunk between two patterns, this would create a ladder of transfers as opposed to a series of overlapping stars or our current single-point transfer.

**Comment by ansoncfit** [comment]
Some amendments to previous comments:

> The newly created route will generate its own transfers to the closest stop on all other patterns

When an added trip pattern re-uses a stop from the baseline network, transfers are not actually rebuilt for that stop when the scenario is processed. One option would be tracking which stops are used by scenarios, then rebuilding transfers for those stops when the scenario is processed. While that would address the second example in this issue, it would not address the first, and it would involve a more invasive change to track the stops then include them in the `findTransfers()` search, which currently iterates simply by:
https://github.com/conveyal/r5/blob/ebbd53b3079858a7ac7fbb32b0119350a15730b2/src/main/java/com/conveyal/r5/transit/TransferFinder.java#L104-L108

> ...filters out the transfer between them because some other pair of northbound/southbound stops has a shorter distance between them.

In this case, the pair of stops is actually the same stop. The last stop of the northbound pattern is closest to the southbound pattern at that stop itself, the first stop of the southbound pattern.

> Currently we only retain one transfer between each pair of patterns... A good intermediate option might be to find the closest stop on each other pattern for each stop in each pattern

I misspoke in our meeting. In fact, we currently find the closest stop on each pattern for each stop.
