### ISSUE TITLE
ShapefileReader finds zero numeric attributes

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#739]
com.conveyal.r5.util.ShapefileReader#numericAttributes filters on `Number.class.isInstance(d.getType().getBinding())`. The binding will be an instance of Class<T> such as Class<Double> which is not an instance of Class<Number>. What we actually want is `Number.class.isAssignableFrom(d.getType().getBinding())`. The result here is that the checks in  com.conveyal.r5.analyst.Grid#fromShapefile() are no-ops and pass silently since everything is zero or multiplied by zero.

I will be fixing this in an upcoming PR handling LTS shapefiles.

**Comment by ansoncfit** [comment]
This has been fixed in https://github.com/conveyal/r5/pull/732/commits/7d7ff78ed4661382b7d498ebde92d6823b426b5c

**Comment by abyrd** [comment]
The patch is present in another branch, but will also be needed in the LTS shapefile work. I'll leave this issue open until we get one or both of those merged to dev.

**Comment by ansoncfit** [comment]
This patch made it into https://github.com/conveyal/r5/tree/v6.5
