### ISSUE TITLE
Frequency offset lookup uses wrong tripScheduleIndex

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#740]
The changes to trip pattern filtering in https://github.com/conveyal/r5/pull/708 (included in v6.4) introduced a bug related to frequency offsets.

Before the changes, inactive and frequency-based services were skipped within the loop over trips, allowing for simple incrementing of `tripScheduleIndex`:
https://github.com/conveyal/r5/blob/v6.2/src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java#L630-L633

But with the changes to iterate over only the active frequency patterns, `tripScheduleIndex` is no longer incremented for inactive services, so an incorrect index (too low) may be used at https://github.com/conveyal/r5/blob/v6.4/src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java#L674

This bug was discovered using the STM (Montreal) GTFS, which has frequency-based trips on the same pattern with different numbers of frequency entries.

We could resolve this by generating frequency offsets only for active services.

**Comment by abyrd** [comment]
We should also add some more assertions that array/list lengths are all equal, and probably some "desert tests" with more strongly varying frequency schedule entries.
