### ISSUE TITLE
/build/libs/r5--all.jar" not found: not found

### ISSUE THREAD

**Issue by ArterialMapping** [conveyal/r5#801]
Anyone have any idea how to fix this error? Still somewhat of a newby to docker, not sure where I went wrong here. 

failed to compute cache key: "/build/libs/r5--all.jar" not found: not found
ERROR: Service 'r5' failed to build : Build failed

**Comment by abyrd** [comment]
Hello, Docker is not an actively supported mode of use for R5 and is not a part of Conveyal's deployment approach. Some R5 users were using docker so we included these files as basic examples, but do not use them ourselves. 

We generally don't provide support for third-party deployments but I believe I see what's happening in your case: If you look at the comments at the top of the Dockerfile, you will see an example where an r5version build argument is supplied. Your error message implies that this argument is empty or not supplied.
