### ISSUE TITLE
Allow configuring the geographic extents of the street layer (currently hard coded to 250000 km2)

### ISSUE THREAD

**Issue by SRN1973** [conveyal/r5#815]
Today I wanted to build a new routing network for the whole of Germany with the currend development version of r5r which is based on R5.

However, I encountered the above mentioned error message.  In the past I was able to build the routing network without any problems. Should this indeed be a newly added constraint for whatever purposes this would according to me be big problem for lots of scientists using software based on your georgeous project for accessibility analyses etc. as it would prevent anyone form using r5r (or R5) for countrywide analysis tasks from now on (e.g. Germany has an area of 357.588 km²).

So please remove this annoying and according to me totally superfluous constraint as soon as possible or timely provide a workaround or parameter that allows R5 to ignore this strange newly added constraint.

**Comment by trevorgerhardt** [comment]
Hi @SRN1973! Thanks for the input. We accept this constraint but I can see how others may not.

If you (or others) would like to contribute to this project to make the constraint customizable please let us know here or by opening a pull request with the desired changes. 

If you do not have the available bandwidth to contribute, then I would recommend using the version of r5 that was previously working for you.

**Comment by ansoncfit** [comment]
As a bit more background, we tune parameters in R5 to meet the needs of subscribers to the Conveyal hosted platform and occasionally add limits to ensure stability of the shared computing environment. In general we do not guarantee backward compatibility for third-party wrapper libraries (see clarifications to the R5 README in #817). 

In this particular case, we will increase the limit to address some recent use cases of platform users. With this increase, I will close this issue for now, but if there are resources to dedicate to a more formally documented API for backward compatibility or configuration, we are open to that discussion.
