### ISSUE TITLE
Coordinate rounding error when checking projected shapefile upload

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#833]
The check at https://github.com/conveyal/r5/blob/44c683941de3035bb4f5de0d60e71bbba27db29f/src/main/java/com/conveyal/analysis/datasource/ShapefileDataSourceIngester.java#L49-L51 recently failed when a user uploaded a shapefile of selected block groups in southern Louisiana (projection NAD 83).

Envelope for the shapefile reader has `maxy = 30.212154999179035`, while `((Geometry) f.getDefaultGeometry()).getEnvelopeInternal()` yields `maxy = 30.21215499917904`. Because of this apparent rounding difference, the feature's envelope is not contained by the shapefile reader's envelope.

**Comment by ansoncfit** [comment]
Just observed this again -- a simple polygon failed, while a similar one just up the street succeeded.

**Comment by abyrd** [comment]
Thanks for the report @ansoncfit and the example files you provided on Slack. There are coordinate transforms taking place, and it's not a given that projecting an envelope around unprojected geometries yields an envelope containing all the geometries projected individually, but for the particular coordinate systems we're using I wouldn't expect that to be a problem (WGS and Mercator axes are parallel to each other).

I'm not really sure what I was trying to check with this assertion - I should have added a comment about what prompted this. Probably the thing to do here is to go back and re-evaluate whether the assertion is needed at all, and if there's any doubt about reliability of envelopes produced by JTS we could build up the envelope from the geometries as they're loaded. In any case it looks like the existing implementation would iterate over all the features more than once.
