### ISSUE TITLE
StreetRouter is slow

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#87]
StreetRouter is really slow for long street searches (e.g. direct street searches in profile routing) after implementation of #84 and #13.

**Comment by mattwigway** [comment]
Looks like this is specifically due to #84.

**Comment by mattwigway** [comment]
Target pruning has helped a lot, but really we should be able to get a continent scale SPT in a few ms.

**Comment by abyrd** [comment]
Revisiting five years later: My sense is that street routing, especially for cars, can still be surprisingly slow. It would be good to profile this again and see if branching due to turn restrictions is at least partially responsible (I think that was our last hypothesis).

**Comment by abyrd** [comment]
Closing, merged into #764.
