### ISSUE TITLE
Polyline Encoder does not exist

### ISSUE THREAD

**Issue by MatthewLehane** [conveyal/r5#871]
When building r5 on my local machine, I have an error relating to the polyline encoder:

https://nexus.axiomalaska.com/nexus/content/repositories/public/

Looks like this page is down or does not exist anymore although it is a dependency for r5? I am unable to access it. Not sure if this is just an issue on my end, I understand you do not provide help to third party installs, I understand if so -

**Comment by abyrd** [comment]
Hi @MatthewLehane, thanks for the report. We are also running into this issue in our automated build. It looks like their repo server is up (see http://nexus.axiomalaska.com/nexus/content/repositories/) but returning 500 error response codes for resources inside the repo.

This is the PR where we patched the polyline-encoder to more recent Geotools and JTS versions, yielding at 0.2 release:
https://github.com/axiom-data-science/polyline-encoder/pull/1
This release was on Axiom's repo. Let's wait a day or two and see if it becomes available again. If not, we can contact them and coordinate.

Digging a bit deeper, we only need this repository to get the dependency `com.axiomalaska:polyline-encoder`, which is only used in `com.conveyal.r5.util.EncodedPolylineSerializer`, which is only used in `com.conveyal.r5.transitive.TransitivePattern` line 23. This is then only used in `com.conveyal.r5.transitive.TransitiveNetwork`, which in turn we only use in `com.conveyal.r5.analyst.cluster.AnalysisWorker#saveTauiMetadata`. So all of these classes and this dependency are only used for one very specific workflow that no one outside Conveyal is likely to ever use. 

You can simply delete EncodedPolylineSerializer and remove the dependency and the repo from the Gradle config, and the whole project should work fine for most use cases.

**Comment by abyrd** [comment]
I have manually copied the artifacts over from the axiomalaska Maven repo to the Conveyal Maven repo. We usually don't use this repo anymore, but it can serve as a source for this artifact until / unless we have another solution. If you just remove the axiomalaska repo from build.gradle (as in https://github.com/conveyal/r5/pull/869/commits/8545de9f2ee12f240e910d42a944c96e57459348) the build should complete.
