### ISSUE TITLE
Feature: time to nth nearest ("dual" accessibility)

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#875]
Users from multiple organizations in California have requested "dual" accessibility measures (e.g. time required to reach some threshold number of opportunities, such as one school or three grocery stores). The TransitCenter Equity Dashboard includes these types of measures (specifically, the time needed to reach the 3rd Grocery Store, 3rd Pharmacy, 1st Urgent Care, 1st Hospital, and 1st College/University).

**Comment by ansoncfit** [comment]
We also had a recent request for this feature in the Netherlands.

**Comment by abyrd** [comment]
Users will often use this feature with many freeform destination layers at once (TransitCenter uses five layers). So we should explore allowing multiple freeform destinations in one regional analysis which may allow big efficiency gains (not running multiple regional analyses), or at least update documentation to explain why gridded destinations or combining all freeform destinations into a single layer is beneficial here.
