### ISSUE TITLE
R5 Local Setup, testOSM() failed

### ISSUE THREAD

**Issue by izk1989** [conveyal/r5#878]
Hi everyone,

I am trying to run Conveyal locally and have an issue when running the gradle runBackend command. The testOSM() test failed with the following errors:

C:\Users\Isaac\conveyal2\r5>gradle runBackend

> Task :test

OSMTest > testOSM() FAILED
    java.lang.RuntimeException at OSMTest.java:19
        Caused by: java.lang.RuntimeException at OSMTest.java:19
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mapdb.Volume$ByteBufferVol (file:/C:/Users/Isaac/.gradle/caches/modules-2/files-2.1/org.mapdb/mapdb/1.0.8/64485a221d9095fc7ab9b50cc34c6b4b58467e2e/mapdb-1.0.8.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.mapdb.Volume$ByteBufferVol
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

596 tests completed, 1 failed, 2 skipped
![r5_testresult1](https://user-images.githubusercontent.com/43076721/226738291-36d70e3c-3708-430b-b325-71319edf2b80.PNG)

[Test results - OSMTest.pdf](https://github.com/conveyal/r5/files/11033533/Test.results.-.OSMTest.pdf)
[Test results - OSMTest2.pdf](https://github.com/conveyal/r5/files/11033534/Test.results.-.OSMTest2.pdf)
[Test results - OSMTest3.pdf](https://github.com/conveyal/r5/files/11033536/Test.results.-.OSMTest3.pdf)

Thanks and appreciate any help on this

**Comment by artursrode** [comment]
Did you manage to solve the issue?

**Comment by abyrd** [comment]
Hi @izk1989 and @artursrode, these errors are probably due to running on newer JVMs which introduced more restrictions on inspecting the internal details of classes. See #760 where we've got changes lined up to migrate to newer JVMs.

Just wondering, could you share how you are using R5? We're always curious what uses people are finding for our OSS projects given the very niche problem domain.

**Comment by abyrd** [comment]
Closing due to no response - assuming it was just JVM version problems as mentioned in comment above.
