### ISSUE TITLE
Inquiry about Significant Differences in r5r and ArcGIS Accessibility Analysis Results

### ISSUE THREAD

**Issue by SeasoningPackkk** [conveyal/r5#883]
I am writing to seek your expertise regarding a perplexing issue I encountered while conducting accessibility analysis using r5r and ArcGIS.
 
The objective of my analysis is to determine the number of facilities accessible within a 15-minute walking distance from the population-weighted centroids of LSOA regions. Both r5r and ArcGIS use the same starting points and the same dataset of destination facilities. I have set the walking speed to 4.8 km/h for both analyses. The only difference lies in ArcGIS, where the road network was manually constructed and topology was checked based on OpenStreetMap data.
 
During the comparison of health and education facilities for the same LSOA regions, I noticed significant discrepancies between r5r and ArcGIS results. For instance, for LSOA E01000886, ArcGIS indicates 74 health-related facilities, while r5r reports an astonishing 204 facilities (a highly surprising number). These discrepancies persist in other randomly selected LSOA regions as well.
 
To validate my findings and understand the cause of these differences, I would like to request assistance with the verification of the decay function "step" (accumulative opportunity) used in r5r. As I noticed, this function only returns the total number of accessible services without specifying which services were actually reached.
 
Considering the consistency of walking ranges and accessible facilities in ArcGIS when cross-referenced with Google Maps' walking time between two points, I find myself perplexed and uncertain about the potential source of the discrepancies.
 
Below is the code and parameter settings I used for r5r analysis for:
 
mode <- c("WALK")
max_walk_time <- 20 # in minutes
travel_time_cutoff <- 15 # in minutes
percentiles <- 50
 
access_education <- accessibility(r5r_core,
                                origins = try,
                                destinations = subset_education,
                                mode = mode,
                                walk_speed = 4.8,
                                opportunities_colnames = c("category"),
                                decay_function = "step",
                                cutoffs = travel_time_cutoff,
                                max_walk_time = max_walk_time,
                                percentiles = percentiles,
                                progress = TRUE)
  return(access_subset)
 
I would highly appreciate any insights, suggestions, or guidance you can provide to resolve this issue and ensure the accuracy of my analysis.
 
Thank you for your time and consideration. I look forward to hearing from you.

**Comment by abyrd** [comment]
Hello, first I would like to clarify that we are not the authors of r5r, which is a wrapper around our r5 project created by a team at IPEA (https://github.com/ipeaGIT/r5r/). We use the r5 library as a core component of our web-based analysis platform, and while we are happy to share the source code to ensure transparency around our methods, we don't typically provide support for third-party reuse and deployment of this code.

I am not quite sure what you mean by "assistance with the verification of the decay function 'step' (accumulative opportunity) used in r5r". You are correct that this function "only returns the total number of accessible services without specifying which services were actually reached". This is the case for all our decay functions, which simply change the weight assigned to each destination. The underlying accessibility calculation is always a sum of reachable destinations. 

In our web-based system we have other modes of analysis which will report the travel time to each different destination, but I don't know how this would be done with r5r.

Base on a quick look at your parameters your request looks correct to me, but I don't know the details of how r5r interacts with r5, and there are many other things including how the input data are prepared that could affect the results.
