### ISSUE TITLE
Adjacent turn restrictions can cause infinite loop

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#89]
I believe that if you have two adjacent turn restrictions, you can cause an infinite loop because the router will ping-pong back and forth down the segment but none of the states will dominate.

**Comment by mattwigway** [comment]
I wrote a test and confirmed this issue exists.

**Comment by mattwigway** [comment]
I suppose that the only real solution is that when there are multiple states with turn restrictions we must compare to see if they have the same turn restrictions.

**Comment by abyrd** [comment]
Closing, merged into #764.
