### ISSUE TITLE
Link edges need to have lengths

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#91]
In this image you can see a triangular section above the bridge where all the cells in a particular column have the same value.

This is probably because cells outside the triangle are being connected to the land and cells within the triangle are being connected to the bridge, but the edges connecting them have almost no cost. Note that this only happens on the north side of the bridge, probably because cells are connected to only one way and therefore inherit the permissions of only that way. There's a pedestrian walkway on the north side of that bridge, but the south side is car-only.

![image](https://cloud.githubusercontent.com/assets/566958/13235772/bc1e7980-d98d-11e5-9e0c-6b86fc94bc85.png)

**Comment by ansoncfit** [comment]
This was addressed in https://github.com/conveyal/r5/pull/427
