### ISSUE TITLE
adjust-frequency modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#93]
We need to have a modification to convert trips to frequency-based (primarily so that we can change the frequencies of trips). The proposed JSON is below, annotated. One thing to note is that this modification is hierarchical; there should only be one per route, and it should wipe all non-frequency trips on the route away and replace them with the described frequency trips. This is to avoid accidentally leaving short-turn trips that aren't getting frequencies specified in the graph.

```
{
  "name": "",
  // GTFS feed ID
  "feed": "kcata",
  // Routes to convert to frequency.
  "routes": [
    "26"
  ],
  // frequency entries for this route
  "entries": [
    {
      // days this is active, starting with Monday. This is represented as a Java bitset, so falses at the end (saturday and sunday) can be omitted
      "days": [
        true,
        true,
        true,
        true,
        true
      ],
      // when this frequency entry starts, seconds since GTFS midnight
      "startTime": 14400,
      // when this frequency entry ends, seconds since GTFS midnight
      "endTime": 21600,
      // headway of this frequency entry, seconds
      "headwaySecs": 900,
      // the trip from which we should copy the pattern and travel times
      "sourceTrip": "4664390"
    },
    {
      "days": [
        true,
        true,
        true,
        true,
        true
      ],
      "startTime": 21600,
      "endTime": 36000,
      "headwaySecs": 600,
      "sourceTrip": "4670120"
    },
    // entire block repeated once for each desired frequency entry (presumably at least one per direction)
    {
      "days": [
        true,
        true,
        true,
        true,
        true
      ],
      "startTime": 36000,
      "endTime": 57600,
      "headwaySecs": 900,
      "sourceTrip": "4670126"
    }
  ],
  "type": "adjust-frequency"
}
```

**Comment by abyrd** [comment]
So this adheres to the principle that only one modification affects each trip by performing the deletion of scheduled trips and adding the new frequencies within the same modification. It looks like the frequency entries must be listed out in detail and they are not inferred from the existing trips. This would be fine for setting the frequency to a chosen number, but what if someone wants to e.g. increase it by 10%? Are we still guessing frequencies from the existing trips? In a way it would actually be much cleaner if we didn't support that.

**Comment by mattwigway** [comment]
I'm opposed to trying to guess frequencies at all.

On Tue, Mar 8, 2016 at 10:46 AM, Andrew Byrd <notifications@github.com>
wrote:

> So this adheres to the principle that only one modification affects each
> trip by performing the deletion of scheduled trips and adding the new
> frequencies within the same modification. It looks like the frequency
> entries must be listed out in detail and they are not inferred from the
> existing trips. This would be fine for setting the frequency to a chosen
> number, but what if someone wants to e.g. increase it by 10%? Are we still
> guessing frequencies from the existing trips? In a way it would actually be
> much cleaner if we didn't support that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/93#issuecomment-193831132>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
Oh great, then we only support just overwriting them / creating them from scratch. That's fine by me until we have a good reason do to otherwise, much less error prone. I know we decided to skip the automated grouping of patterns and just ask the user, but this is even better.

**Comment by mattwigway** [comment]
To clarify, the `sourceTrip` is only used to source pattern and travel times. All trips on the route will be removed to avoid confusion with some trips not being converted. New trips and frequency entries will be created based on the modification, which means that some of the trip patterns will be retained; some may not be.

**Comment by abyrd** [comment]
Someone may want to frequency convert only the peak period service and leave the off-peak as-is. In order to do that, when applying this modification type we could drop only the trips that occur during the specified frequency entries. This is an advanced feature though and won't be needed right away. We could add a switch later.

**Comment by abyrd** [comment]
I can sort of see frequency adjustment working without a frequency conversion if we specified a zero point (as mentioned in other modification tickets). But that re-opens the pattern grouping can of worms that you've effectively sealed closed here. So let's leave it as-is.

**Comment by mattwigway** [comment]
Here's an updated version of the format:

```
    {
      "type": "adjust-frequency",
      "route": "0c86d09743e1420c969ab653e61062ce_0:24",
      "entries": [
        {
          "monday": true,
          "tuesday": true,
          "wednesday": true,
          "thursday": true,
          "friday": true,
          "saturday": false,
          "sunday": false,
          "startTime": 25200,
          "endTime": 79200,
          "headwaySecs": 600,
          "sourceTrip": "0c86d09743e1420c969ab653e61062ce_0:4401633"
        },
        {
          "monday": false,
          "tuesday": false,
          "wednesday": false,
          "thursday": false,
          "friday": false,
          "saturday": true,
          "sunday": true,
          "startTime": 25200,
          "endTime": 79200,
          "headwaySecs": 1200,
          "sourceTrip": "0c86d09743e1420c969ab653e61062ce_0:4401596"
        }
      ]
    }
```

**Comment by mattwigway** [comment]
@abyrd thoughts?
