### ISSUE TITLE
remove-stops modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#96]
```
    {
      "type": "remove-stops",
      "feed": "kcata",
      // routes from which to remove stops, ignored if trips is not null
      "routes": [
        "58"
      ],
      // trips from which to remove stops
      "trips": [
        "4670170",
        "4669738"
      ],
      // stops to remove
      "stops": [
        "56001",
        "5600167",
        "5600168",
        "5600169",
        "5600170",
        "5600171"
      ],
      "name": ""
    }
```

**Comment by mattwigway** [comment]
Hmm, minor issue here: if you remove stops from some but not all trips on a pattern, you've actually created another pattern.

**Comment by mattwigway** [comment]
Also, there's no way to remove one instance of a stop that occurs twice in a loop route. The obvious solution it to use stop indices rather than stop IDs but that only works if all the trips have the same pattern, which frequently they won't. Maybe no one will ever want to do that though.

**Comment by abyrd** [comment]
We could simply not have a way to remove stops from individual trips. If you remove them from an entire route, you automatically remove them from every trip in every pattern.

**Comment by abyrd** [comment]
As far as I know this will be used for truncating or skipping sections of routes. I don't know of any case where you'd want to remove one instance of a stop and not another within the same trip. Good to think about for documentation / design purposes, but I think we can just not support that case.

**Comment by abyrd** [comment]
Removing a stop also means removing its dwell time, which risks disrupting timed transfers. I'm thinking all of these modifications should have a "zero point" parameter where you can specify which stop's stop times are guaranteed to remain unchanged after the modification. This would be the beginning of the line unless otherwise specified in the UI.

**Comment by abyrd** [comment]
In its final form:

```JSON
{
      "type": "remove-stops",
      "comment": "remove some stops from a route",
      // Routes from which to remove stops. Must specify only one of routes or trips.
      "routes": [
        "kcata:58"
      ],
      // Trips from which to remove stops. Must specify only one of routes or trips.
      "trips": [
        "kcata:4670170",
        "kcata:4669738"
      ],
      // stops to remove
      "stops": [
        "kcata:56001",
        "kcata:5600167",
        "kcata:5600168",
        "kcata:5600169",
        "kcata:5600170",
        "kcata:5600171"
      ]
    }
```
