### ISSUE TITLE
adjust-dwell-time modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#97]
Adjust dwell times on a route.

```
{
      "type": "adjust-dwell-time",
      // feed ID
      "feed": "kcata",
      // route ID, ignored if trip IDs are specified
      "routes": [
        "15"
      ],
      // Trip IDs to modify
      "trips": [
        "4666048",
        "4666068"
      ],
      // stops at which to adjust dwell times, if left null should affect all stops
      "stops": [
        "1200015",
        "1200016",
        "1200018",
        "1200019"
      ],
      // if scale = false, new dwell time in seconds; if scale = true, multiplier for dwell times
      "value": "15",
      // see above comment
      "scale": false,
      "name": ""
    }
```

**Comment by mattwigway** [comment]
This has the same problem as #96 in that you can't specify something that affects only one instance of a stop that appears more than once in a pattern.

**Comment by abyrd** [comment]
Again, I'm wondering if we want boolean switches with generic "value" fields, or something where the mere presence of a field `"scale": 1.5` causes the dwells to be scaled, and `"dwellSecs": 30` causes it to be set rather than scaled.

**Comment by abyrd** [comment]
And again wondering (just brainstorming here) whether this could be lumped into a generic add/update modification along with frequency-convert and add-trip-pattern. Nah, this needs to affect only certain stops and the meaning is much clearer if we don't lump too many operations together into mega-generic classes.

**Comment by abyrd** [comment]
If the hop times remain the same and dwells are lengthened or shortened, then doesn't this modification risk disrupting timed transfers? Should it then result in frequency conversion?

**Comment by abyrd** [comment]
Also, I can imagine someone wanting to adjust both the dwell times and the speeds on a single route. That would defy the one-modification-per-trip principle. Should the two modifications be merged?

**Comment by mattwigway** [comment]
Well the thing about dwell times and speeds is that they're commutative, so
having multiple modifications doesn't matter.

On Thu, Mar 10, 2016 at 5:57 PM, Andrew Byrd <notifications@github.com>
wrote:

> Also, I can imagine someone wanting to adjust both the dwell times and the
> speeds on a single route. That would defy the one-modification-per-trip
> principle. Should the two modifications be merged?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/97#issuecomment-195088626>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
Assuming your fixed zero-point is well defined, yes order wouldn't matter. And I guess by default the zero point is the first stop in the trips. I was thinking of "one modification per trip" as an enforceable invariant. If we make this into a pragmatic thing and apply it only where we expect problems, that might work. But we need to state clearly whether we do in fact allow multiple modifications per trip.

**Comment by abyrd** [comment]
Final form:

```
{
      "type": "adjust-dwell-time",
      "comment": "change some dwell times",
      // Route IDs to modify. Specify routes or trips but not both.
      "routes": [ "kcata:15" ],
      // Trip IDs to modify.
      "trips": [
        "kcata:4666048",
        "kcata:4666068"
      ],
      // Stops at which to adjust dwell times, if left null all stops are affected.
      "stops": [
        "kcata:1200015",
        "kcata:1200016",
        "kcata:1200018",
        "kcata:1200019"
      ],
      // Time that the vehicle will wait at each stop. Specify dwellSecs or scale, but not both.
      "dwellSecs": "15",
      // Multiplier for dwell times. 
      "scale": 1.5
}
```
