### ISSUE TITLE
adjust-speed modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#98]
We need to adjust speeds on all or part of a route:

```
{
      "name": "Add exclusive lanes downtown",
      // feed ID
      "feed": "kcata",
      // route IDs, ignored if trips are specified
      "routes": [
        "47"
      ],
      // trips to modify
      "trips": [
        "4666308",
        "4666348"
      ],

      // if true, scale existing speeds; if false, set a new speed in km/h
      "scale": true,
      // depending on value of above, either scale factor (larger is faster), or new speed in km/h
      "value": 1.5,
      "type": "adjust-speed",
      // stops _at the start of_ the hops to which this modification should be applied
      // if null, all hops should be modified.
      "stops": [
        "10",
        "5400089",
        "290053",
        "290091",
        "2800191",
        "2800195",
        "2220019",
        "2220021"
      ]
    }
```

**Comment by mattwigway** [comment]
Again, has the same problem as #96 with stop IDs being potentially ambiguous on loop routes.

**Comment by abyrd** [comment]
Is it better to have a general-purpose "value" property and a "scale" boolean, or just two properties "scale" and "speedKph" which are both numbers (if speedKph is specified speed is set, otherwise it is scaled by the factor in the scale property).

**Comment by abyrd** [comment]
Regarding stops on loop routes, I'd again say we can just not support that case, providing a short note in the javadoc explaining that this is a known limitation.

**Comment by mattwigway** [comment]
There's another problem here, which is that we're using stop IDs to represent hops, which is problematic when you're selecting both directions of a route. Consider this case:

![image](https://cloud.githubusercontent.com/assets/566958/13603257/dd5f3c9c-e509-11e5-9f4c-53676d500d6c.png)

Suppose you want to speed up both the eastbound and westbound patterns from stop 2 to stop 3, because you're adding a dedicated lane there. If you use a single modification, do you specify stop 2, or stop 3?

One option is instead to specify hops by using _both_ their start and end stop. So for example the stops section of this modification would be:

```
stops: [
  ["2", "3"],
  ["3", "2"]
]
```

Of course this does not allow easily/directly specifying that the speed change does not affect an entire hop. For example, consider an express train running between two city centers that travels at conventional rail speeds in the city center, and at high-speed rail speeds in the countryside. The entire route is a single hop with variable speed. Of course we could do this on the client side by generating multiple modifications, setting an individual speed for each hop that is partially covered. Otherwise we have to do annoying geographic intersection operations in r5. @abyrd, thoughts?

**Comment by abyrd** [comment]
Yeah, I ran into this hops-not-stops problem before and as a short term solution just sped up all segments after the specified stops. It creates a slightly asymmetric result and is roughly right, but not acceptable for the final version of the modification. 

Instead of specifying each hop with its start/end stopId, what if we specify multi-stop intervals:

```
stopIntervals: [
  ["1", "3"],
  ["3", "1"]
]
```

That would match the left 2/3 of the route in both directions. The other possibility is to do geographic intersection on the workers, which is not really that complicated but does seem like an error prone last resort.

**Comment by mattwigway** [comment]
The code in the UI to select multi-stop intervals is a bit more complicated
than that to select single hops. Is there a compelling reason not to just
do single hops?

On Tue, Mar 8, 2016 at 11:32 AM, Andrew Byrd <notifications@github.com>
wrote:

> Yeah, I ran into this hops-not-stops problem before and as a short term
> solution just sped up all segments after the specified stops. It creates a
> slightly asymmetric result and is roughly right, but not acceptable for the
> final version of the modification.
>
> Instead of specifying each hop with its start/end stopId, what if we
> specify multi-stop intervals:
>
> stopIntervals: [
>   ["1", "3"],
>   ["3", "1"]
> ]
>
> That would match the left 2/3 of the route in both directions. The other
> possibility is to do geographic intersection on the workers, which is not
> really that complicated but does seem like an error prone last resort.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/98#issuecomment-193851659>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
Of course we could support multi-hop intervals but the UI could just code
everything as lists of sequential single hops.

On Tue, Mar 8, 2016 at 11:37 AM, Matthew Wigginton Conway <
matt@indicatrix.org> wrote:

> The code in the UI to select multi-stop intervals is a bit more
> complicated than that to select single hops. Is there a compelling reason
> not to just do single hops?
>
> On Tue, Mar 8, 2016 at 11:32 AM, Andrew Byrd <notifications@github.com>
> wrote:
>
>> Yeah, I ran into this hops-not-stops problem before and as a short term
>> solution just sped up all segments after the specified stops. It creates a
>> slightly asymmetric result and is roughly right, but not acceptable for the
>> final version of the modification.
>>
>> Instead of specifying each hop with its start/end stopId, what if we
>> specify multi-stop intervals:
>>
>> stopIntervals: [
>>   ["1", "3"],
>>   ["3", "1"]
>> ]
>>
>> That would match the left 2/3 of the route in both directions. The other
>> possibility is to do geographic intersection on the workers, which is not
>> really that complicated but does seem like an error prone last resort.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/conveyal/r5/issues/98#issuecomment-193851659>.
>>
>
>
>
> --
> Matthew Wigginton Conway [WIG-in-tun CON-way]
> Transportation Analytics/Open Source
> Washington, DC
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
Or, another possibility that's totally unambiguous is to list out the entire stop sequence of the parts to be modified:

```
stopIntervals: [
  ["1", "2", "3"],
  ["3", "2", "1"]
]
```

About your other question (adjusting only part of a hop) I think we can just not support that. You can only get on or off a vehicle at stops anyway, so we can still get good results if the user manually works out how the segment is split up, acceleration and deceleration etc.

**Comment by mattwigway** [comment]
Right, and if we want to make the UI slick we can even automatically
calculate some of that stuff in the editor.

On Tue, Mar 8, 2016 at 11:39 AM, Andrew Byrd <notifications@github.com>
wrote:

> Or, another possibility that's totally unambiguous is to list out the
> entire stop sequence of the parts to be modified:
>
> stopIntervals: [
>   ["1", "2", "3"],
>   ["3", "2", "1"]
> ]
>
> About your other question (adjusting only part of a hop) I think we can
> just not support that. You can only get on or off a vehicle at stops
> anyway, so we can still get good results if the user manually works out how
> the segment is split up, acceleration and deceleration etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/98#issuecomment-193854486>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
After further discussion, listing single hops between adjacent stops is the best solution. It's unambiguous and doesn't require any fancy matching code in R5.

**Comment by abyrd** [comment]
After a few revisions removing modification-wide feed ID:

```
{
      "name": "Add exclusive lanes downtown",
      // Route IDs to which the modification applies. Specify only one of routes or trips.
      "routes": [
        "kcata:47"
      ],
      // Trips to modify. Specify only one of routes or trips.
      "trips": [
        "kcata:4666308",
        "kcata:4666348"
      ],
      // If supplied, scale existing speeds by this factor. Supply only one of scale or speedKph.
      "scale": 1.5,
      // If supplied, set the speed rather than scaling it. Supply only one of scale or speedKph.
      "speedKph": 50,
      "type": "adjust-speed",
      // Hops which should have their speed set or scaled. If null, all hops should be modified.
      // Each hop is a pair of stop IDs (from/to) and the hop specification is directional.
      "stops": [
        ["kcata:10", "kcata:5400089"],
        ["kcata:290053", "kcata:290091"]
      ]
    }
}

**Comment by abyrd** [comment]
The absolute speed parameter in the adjust-speed modification requires the server to know the inter-stop spacings. We have decided to just leave it out.

**Comment by mattwigway** [comment]
Let's change the stops parameter to be called hops, since that's what it actually represents.

**Comment by abyrd** [comment]
I think "hops" is jargon specific to our immediate entourage, that originated with GraphServer. Brandon named a variable TripHops probably as a incidental reference to the 1990s musical genre. But I guess it's as good a term as any.

**Comment by abyrd** [comment]
Positional semantics are generally bad, and JSON arrays allow any number of elements. Just for clarity, what if the hops look like this:

```
"hops": [
  {
    "from": "kcata:10", 
    "to": "kcata:5400089"
  },
  {
    "from": "kcata:290053", 
    "to": "kcata:290091"
  }
]
```

**Comment by mattwigway** [comment]
No objections, gzip will make that tiny.

On Thu, Mar 31, 2016 at 6:30 AM, Andrew Byrd <notifications@github.com>
wrote:

> Positional semantics are generally bad, and JSON arrays allow any number
> of elements. Just for clarity, what if the hops look like this:
>
> "hops": [
>   {
>     "from": "kcata:10",
>     "to": "kcata:5400089"
>   },
>   {
>     "from": "kcata:290053",
>     "to": "kcata:290091"
>   }
> ]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/98#issuecomment-203871728>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
Keeping the array form for now since it's already in place.
